In [2]:
import torch
import torch.nn as nn

class BinaryClassifier(nn.Module):
    def __init__(self, input_size, dropout_rate=0.2, hidden_layers=[256, 128, 64]):
        super().__init__()

        layerlist = []
        n_in = input_size

        for h in hidden_layers:
            layerlist += [
                nn.Linear(n_in, h),
                nn.BatchNorm1d(h),
                nn.ReLU(inplace=True),
                nn.Dropout(dropout_rate),
            ]
            n_in = h

        # Final output layer: 1 logit for binary classification
        layerlist.append(nn.Linear(n_in, 1))

        self.network = nn.Sequential(*layerlist)

        # Better initialization (same as before)
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.kaiming_uniform_(module.weight, nonlinearity='relu')
                nn.init.zeros_(module.bias)

    def forward(self, x):
        # shape: (batch_size, 1) → squeeze to (batch_size,)
        logits = self.network(x).squeeze(-1)
        return logits


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold

# 0) Load ALREADY-SCALED binary dataset
df_binary = pd.read_csv("artifacts/final_train_scaled_binary_clustered.csv")

TARGET_COL = "MP_binary_high"

# Exclude non-features
exclude = {"SMILES", TARGET_COL, "MW", "MP", "MP_category_default", "Structure_Cluster"}

# Use only numeric feature columns
num_cols = df_binary.select_dtypes(include=[np.number]).columns
feature_cols = [c for c in num_cols if c not in exclude]

# Build X/y
X = df_binary[feature_cols].to_numpy(np.float32)
y = df_binary[TARGET_COL].to_numpy(np.float32)

# Stratification labels (cluster)
y_strat = df_binary["Structure_Cluster"].astype(str).to_numpy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("n features:", len(feature_cols))
print("Label counts:", dict(zip(*np.unique(y, return_counts=True))))

# 1) Fix folds once
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
folds = [(tr_idx, val_idx) for tr_idx, val_idx in skf.split(X, y_strat)]
print("Built folds:", len(folds))


X shape: (17625, 202)
y shape: (17625,)
n features: 202
Label counts: {np.float32(0.0): np.int64(16853), np.float32(1.0): np.int64(772)}
Built folds: 10


In [ ]:
from sklearn.metrics import accuracy_score
from pathlib import Path

#Source: https://stackoverflow.com/questions/71998978/early-stopping-in-pytorch

# Early Stopping Based on Validation Loss
class EarlyStopper:

    # If the val loss has not been improved (i.e. stayed the same or got worse) for 20 epochs in a row, the training of the model is stopped.
    def __init__(self, patience=30, min_delta=0):
        self.patience = int(patience)
        self.min_delta = float(min_delta)
        self.counter = 0
        self.best_loss = float('inf')
        self.stop = False
        self.stop_epoch = None  # remember which epoch we stopped on (for plotting)

    def early_stop(self, val_loss, epoch=None):

        #For each epoch, checks if the validation loss has improved, we reset the counter.
        # We increase the counter if there is no improvement. Once the counter reaches the patience, we stop and remember the epoch.

        # Improvement means the loss decreased by more than min_delta
        if (self.best_loss - val_loss) > self.min_delta:
            self.best_loss = val_loss
            self.counter = 0
        else:
            # No meaningful improvement this epoch
            self.counter += 1
            if self.counter >= self.patience:
                self.stop = True
                self.stop_epoch = epoch
        return self.stop
    

from scipy.special import expit  # stable sigmoid

def save_checkpoint(
    model,
    optimizer,
    epoch,
    train_loss,
    val_loss,
    y_train,
    y_val,
    val_loader,
    fold_idx,
    checkpoint_dir,
    checkpoint_tracking,
    is_final=False,
):
    # Put model in eval mode and collect logits
    model.eval()
    all_logits = []
    with torch.no_grad():
        for xb, _ in val_loader:
            logits = model(xb).cpu().numpy()
            all_logits.append(logits)

    logits_val = np.concatenate(all_logits)   # shape (N,)
    probs_val  = expit(logits_val)            # stable sigmoid
    preds_val  = (probs_val >= 0.5).astype(int)

    # y_val expected as numpy 0/1
    y_val_np = np.asarray(y_val).astype(int)

    # Classification metric: accuracy
    acc = accuracy_score(y_val_np, preds_val)

    # Filename
    if is_final:
        checkpoint_filename = f"checkpoint_epoch_{epoch:03d}_final.pt"
    else:
        checkpoint_filename = f"checkpoint_epoch_{epoch:03d}.pt"

    checkpoint_path_full = Path(checkpoint_dir) / checkpoint_filename

    # Save checkpoint (weights + optimizer + losses + metric)
    checkpoint_data = {
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "train_loss": train_loss,
        "val_loss": val_loss,
        "accuracy": acc,
        "fold_idx": fold_idx,
        "is_final": is_final,
    }
    torch.save(checkpoint_data, checkpoint_path_full)

    # Track info for CSV
    checkpoint_info = {
        "Fold": fold_idx,
        "Epoch": epoch,
        "Checkpoint_Filename": checkpoint_filename,
        "Checkpoint_Path": str(checkpoint_path_full),
        "Train_Loss": round(train_loss, 6),
        "Val_Loss": round(val_loss, 6),
        "Accuracy": round(acc, 6),
        "Is_Final": is_final,
    }
    checkpoint_tracking.append(checkpoint_info)

    checkpoint_type = "Final" if is_final else "Regular"
    print(
        f"[Fold {fold_idx}] {checkpoint_type} checkpoint saved at epoch {epoch} - "
        f"Val Loss: {val_loss:.4f} | Acc: {acc:.4f}"
    )
    return True


In [5]:
import copy
import numpy as np
import pandas as pd
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

from sklearn.metrics import accuracy_score


def evaluate_fold(
    trial,
    fold_idx,
    X_train_scaled,
    y_train,
    X_val_scaled,
    y_val,
    hidden_layers,
    learning_rate,
    batch_size,
    dropout_rate,
    weight_decay,
    max_epochs=10**9,
    patience=30,
    min_delta=0,
    save_checkpoints=True,
    checkpoint_dir="checkpoints_classifier",
    save_every_n_epochs=15,
):

    device = torch.device("cpu")
    print(f"Fold {fold_idx}: Training on cpu (binary classifier, BCELoss)")

    # ---- checkpoints ----
    checkpoint_tracking = []
    if save_checkpoints:
        checkpoint_path = Path(checkpoint_dir)
        checkpoint_path.mkdir(parents=True, exist_ok=True)
        fold_checkpoint_dir = checkpoint_path / f"fold_{fold_idx}"
        fold_checkpoint_dir.mkdir(parents=True, exist_ok=True)
        print(f"Checkpoints will be saved to: {fold_checkpoint_dir}")

    # ---- tensors (y must be float 0/1) ----
    X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32).to(device)
    y_train_tensor = torch.tensor(y_train, dtype=torch.float32).to(device)
    X_val_tensor   = torch.tensor(X_val_scaled, dtype=torch.float32).to(device)
    y_val_tensor   = torch.tensor(y_val, dtype=torch.float32).to(device)

    train_loader = DataLoader(
        TensorDataset(X_train_tensor, y_train_tensor),
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
    )
    val_loader = DataLoader(
        TensorDataset(X_val_tensor, y_val_tensor),
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
    )

    # ---- model + BCELoss ----
    model = BinaryClassifier(
        input_size=X_train_scaled.shape[1],
        hidden_layers=hidden_layers,
        dropout_rate=dropout_rate,
    ).to(device)

    criterion = nn.BCELoss()  # new criterion
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=10)

    early_stopper = EarlyStopper(patience=patience, min_delta=min_delta)

    best_val_loss = float("inf")
    best_state = copy.deepcopy(model.state_dict())

    train_losses, val_losses = [], []
    stop_epoch = None

    # ---- training loop ----
    for epoch in range(1, max_epochs + 1):
        model.train()
        train_loss = 0.0

        for xb, yb in train_loader:
            optimizer.zero_grad()

            logits = model(xb)                 # (batch,)
            probs  = torch.sigmoid(logits)     # (batch,) in [0,1]  <-- REQUIRED for BCELoss
            loss   = criterion(probs, yb)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
            optimizer.step()

            train_loss += loss.item()

        train_loss /= len(train_loader)
        train_losses.append(train_loss)

        # ---- validation ----
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_loader:
                logits = model(xb)
                probs  = torch.sigmoid(logits)
                loss   = criterion(probs, yb)
                val_loss += loss.item()

        val_loss /= len(val_loader)
        val_losses.append(val_loss)

        scheduler.step(val_loss)

        # track best
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = copy.deepcopy(model.state_dict())

        # checkpoints (your existing save_checkpoint() computes sigmoid/acc, so it still works)
        if save_checkpoints and (epoch % save_every_n_epochs == 0 or epoch == 1):
            save_checkpoint(
                model, optimizer, epoch, train_loss, val_loss,
                y_train, y_val, val_loader,
                fold_idx, fold_checkpoint_dir, checkpoint_tracking,
                is_final=False
            )

        # early stopping
        if early_stopper.early_stop(val_loss, epoch=epoch):
            stop_epoch = early_stopper.stop_epoch
            print(f"[Fold {fold_idx}] Early stopping at epoch {stop_epoch} (best Val Loss: {best_val_loss:.4f})")

            # final checkpoint if we didn't just save one
            if save_checkpoints and epoch % save_every_n_epochs != 0 and epoch != 1:
                save_checkpoint(
                    model, optimizer, epoch, train_loss, val_loss,
                    y_train, y_val, val_loader,
                    fold_idx, fold_checkpoint_dir, checkpoint_tracking,
                    is_final=True
                )
            break

        if epoch % 50 == 0 or epoch == 1:
            print(f"[Fold {fold_idx}] Epoch {epoch:4d} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | ES {early_stopper.counter}/{patience}")

    # ---- load best ----
    model.load_state_dict(best_state)
    model.eval()

    # save checkpoint tracking csv
    if save_checkpoints and checkpoint_tracking:
        df_ckpt = pd.DataFrame(checkpoint_tracking)
        df_ckpt.to_csv(fold_checkpoint_dir / f"fold_{fold_idx}_checkpoints_classifier.csv", index=False)

    # ---- final accuracy on val set (best model) ----
    all_logits = []
    with torch.no_grad():
        for xb, _ in val_loader:
            all_logits.append(model(xb).cpu().numpy())
    logits_val = np.concatenate(all_logits)
    probs_val  = 1 / (1 + np.exp(-logits_val))
    preds_val  = (probs_val >= 0.5).astype(int)

    y_val_np = np.asarray(y_val).astype(int)
    acc = accuracy_score(y_val_np, preds_val)

    return best_val_loss, acc, model, train_losses, val_losses, stop_epoch

import time
import numpy as np
from pathlib import Path

trial_times = []

def objective(trial):
    # Suggest hyperparameters
    dropout_rate  = trial.suggest_float("dropout_rate",  0.2, 0.5)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-3, log=True)
    weight_decay  = trial.suggest_float("weight_decay",  1e-6, 1e-2, log=True)
    batch_size    = trial.suggest_categorical("batch_size", [16, 32, 64])

    # Hidden layers (same logic)
    h1 = trial.suggest_categorical("h1", [64, 96, 128, 160, 192, 224, 256])
    h2 = max(h1 // 2, 4)
    h3 = max(h2 // 2, 2)
    hidden_layers = [h1, h2, h3]

    start = time.perf_counter()

    val_losses = []
    accs = []

    # Run this hyperparameter combo across all folds
    for fold_idx, (tr_idx, val_idx) in enumerate(folds):
        X_train_scaled = X[tr_idx]
        y_train        = y[tr_idx]
        X_val_scaled   = X[val_idx]
        y_val          = y[val_idx]

        # Put classifier checkpoints in a classifier-specific folder
        trial_checkpoint_root = Path("checkpoints_binary_classifier") / f"trial_{trial.number:03d}"

        best_val_loss, acc, _, _, _, _ = evaluate_fold(
            trial=trial,
            fold_idx=fold_idx,
            X_train_scaled=X_train_scaled,
            y_train=y_train,
            X_val_scaled=X_val_scaled,
            y_val=y_val,
            learning_rate=learning_rate,
            batch_size=batch_size,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
            weight_decay=weight_decay,
            save_checkpoints=True,
            checkpoint_dir=trial_checkpoint_root,
        )

        val_losses.append(best_val_loss)
        accs.append(acc)

    elapsed = (time.perf_counter() - start) / 60.0
    trial_times.append(elapsed)
    print(f"Trial {trial.number} finished in {elapsed:.2f} minutes")

    avg_val_loss = float(np.mean(val_losses))
    avg_acc      = float(np.mean(accs))

    print(f"Trial {trial.number}: Avg Val Loss = {avg_val_loss:.4f} | Avg Acc = {avg_acc:.4f}")

    # Optuna minimizes this
    return avg_val_loss

In [6]:
import optuna

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)

best_params = study.best_params
print(best_params)

/opt/anaconda3/envs/Surabie_S_clean_v2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2025-12-14 19:20:06,835] A new study created in memory with name: no-name-3cfeba63-94fb-4b47-88af-f8af1094b462


Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_000/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.4130 | Acc: 0.9217
[Fold 0] Epoch    1 | Train Loss: 0.5469 | Val Loss: 0.4130 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1126 | Acc: 0.9586
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1042 | Acc: 0.9592
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1018 | Acc: 0.9660
[Fold 0] Epoch   50 | Train Loss: 0.0954 | Val Loss: 0.1005 | ES 4/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1010 | Acc: 0.9665
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1004 | Acc: 0.9671
[Fold 0] Early stopping at epoch 76 (best Val Loss: 0.0990)
[Fold 0] Final checkpoint saved at epoch 76 - Val Loss: 0.1006 | Acc: 0.9660
Fold 1: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_0

[I 2025-12-14 19:24:47,644] Trial 0 finished with value: 0.10590743351328587 and parameters: {'dropout_rate': 0.2614526550050616, 'learning_rate': 0.00019830053261358507, 'weight_decay': 2.4896850308951163e-05, 'batch_size': 64, 'h1': 96}. Best is trial 0 with value: 0.10590743351328587.


[Fold 9] Early stopping at epoch 73 (best Val Loss: 0.0978)
[Fold 9] Final checkpoint saved at epoch 73 - Val Loss: 0.1032 | Acc: 0.9682
Trial 0 finished in 4.68 minutes
Trial 0: Avg Val Loss = 0.1059 | Avg Acc = 0.9604
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_001/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1307 | Acc: 0.9563
[Fold 0] Epoch    1 | Train Loss: 0.2430 | Val Loss: 0.1307 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.0937 | Acc: 0.9654
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1033 | Acc: 0.9648
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1071 | Acc: 0.9637
[Fold 0] Early stopping at epoch 45 (best Val Loss: 0.0937)
Fold 1: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_001/fold_1
[Fold 1] Regular checkpoint saved at epoch 1 - Val Loss: 0.1271 | Acc: 0.96

[I 2025-12-14 19:37:30,564] Trial 1 finished with value: 0.10249554413374946 and parameters: {'dropout_rate': 0.40868398377036486, 'learning_rate': 0.0006993877326082944, 'weight_decay': 3.222453491315206e-05, 'batch_size': 32, 'h1': 224}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 41 (best Val Loss: 0.0946)
[Fold 9] Final checkpoint saved at epoch 41 - Val Loss: 0.1058 | Acc: 0.9682
Trial 1 finished in 12.72 minutes
Trial 1: Avg Val Loss = 0.1025 | Avg Acc = 0.9618
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_002/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.9005 | Acc: 0.1554
[Fold 0] Epoch    1 | Train Loss: 1.1820 | Val Loss: 0.9005 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.2022 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1522 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1486 | Acc: 0.9563
[Fold 0] Epoch   50 | Train Loss: 0.1973 | Val Loss: 0.1449 | ES 1/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1371 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1278 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at

[I 2025-12-14 20:02:49,998] Trial 2 finished with value: 0.11745377793391068 and parameters: {'dropout_rate': 0.4277356687801487, 'learning_rate': 1.902568781484142e-05, 'weight_decay': 1.9334138420302206e-05, 'batch_size': 16, 'h1': 96}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 208 (best Val Loss: 0.1031)
[Fold 9] Final checkpoint saved at epoch 208 - Val Loss: 0.1062 | Acc: 0.9625
Trial 2 finished in 25.32 minutes
Trial 2: Avg Val Loss = 0.1175 | Avg Acc = 0.9562
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_003/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1469 | Acc: 0.9563
[Fold 0] Epoch    1 | Train Loss: 0.2902 | Val Loss: 0.1469 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1016 | Acc: 0.9671
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1054 | Acc: 0.9648
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1047 | Acc: 0.9637
[Fold 0] Early stopping at epoch 49 (best Val Loss: 0.0954)
[Fold 0] Final checkpoint saved at epoch 49 - Val Loss: 0.1128 | Acc: 0.9631
Fold 1: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_003/fo

[I 2025-12-14 20:08:11,246] Trial 3 finished with value: 0.10384463779545124 and parameters: {'dropout_rate': 0.2925571033986961, 'learning_rate': 0.00039094527327707026, 'weight_decay': 2.0944793944607498e-05, 'batch_size': 32, 'h1': 192}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 49 (best Val Loss: 0.0939)
[Fold 9] Final checkpoint saved at epoch 49 - Val Loss: 0.1074 | Acc: 0.9705
Trial 3 finished in 5.35 minutes
Trial 3: Avg Val Loss = 0.1038 | Avg Acc = 0.9607
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_004/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1346 | Acc: 0.9563
[Fold 0] Epoch    1 | Train Loss: 0.2898 | Val Loss: 0.1346 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.0980 | Acc: 0.9609
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1027 | Acc: 0.9603
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1231 | Acc: 0.9620
[Fold 0] Epoch   50 | Train Loss: 0.0516 | Val Loss: 0.1298 | ES 26/30
[Fold 0] Early stopping at epoch 54 (best Val Loss: 0.0945)
[Fold 0] Final checkpoint saved at epoch 54 - Val Loss: 0.1283 | Acc: 0.9597
Fold 1: Training on cpu (binary classifier, BCELoss)
Chec

[I 2025-12-14 20:17:32,872] Trial 4 finished with value: 0.1048223070068551 and parameters: {'dropout_rate': 0.30677681011114394, 'learning_rate': 0.0007846739158519293, 'weight_decay': 0.00010788149817656794, 'batch_size': 64, 'h1': 224}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 43 (best Val Loss: 0.0973)
[Fold 9] Final checkpoint saved at epoch 43 - Val Loss: 0.1144 | Acc: 0.9682
Trial 4 finished in 9.36 minutes
Trial 4: Avg Val Loss = 0.1048 | Avg Acc = 0.9609
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_005/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.6990 | Acc: 0.6222
[Fold 0] Epoch    1 | Train Loss: 0.7835 | Val Loss: 0.6990 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.3652 | Acc: 0.9450
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.2097 | Acc: 0.9592
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1521 | Acc: 0.9597
[Fold 0] Epoch   50 | Train Loss: 0.1554 | Val Loss: 0.1411 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1320 | Acc: 0.9620
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1233 | Acc: 0.9603
[Fold 0] Regular checkpoint saved at 

[I 2025-12-14 21:15:31,880] Trial 5 finished with value: 0.11047819389828614 and parameters: {'dropout_rate': 0.24978569056535002, 'learning_rate': 1.0286209212611935e-05, 'weight_decay': 4.380490981173294e-06, 'batch_size': 64, 'h1': 256}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 177 (best Val Loss: 0.1056)
[Fold 9] Final checkpoint saved at epoch 177 - Val Loss: 0.1071 | Acc: 0.9642
Trial 5 finished in 57.98 minutes
Trial 5: Avg Val Loss = 0.1105 | Avg Acc = 0.9602
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_006/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.9036 | Acc: 0.1815
[Fold 0] Epoch    1 | Train Loss: 1.0505 | Val Loss: 0.9036 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.7061 | Acc: 0.4974
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.5158 | Acc: 0.8843
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.3962 | Acc: 0.9404
[Fold 0] Epoch   50 | Train Loss: 0.3910 | Val Loss: 0.3554 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.2994 | Acc: 0.9569
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.2472 | Acc: 0.9569
[Fold 0] Regular checkpoint saved 

[I 2025-12-14 21:31:15,901] Trial 6 finished with value: 0.12107933358555392 and parameters: {'dropout_rate': 0.3033619859670642, 'learning_rate': 1.1279097427135107e-05, 'weight_decay': 7.382714409409935e-06, 'batch_size': 64, 'h1': 64}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 325 (best Val Loss: 0.1187)
[Fold 9] Final checkpoint saved at epoch 325 - Val Loss: 0.1197 | Acc: 0.9625
Trial 6 finished in 15.73 minutes
Trial 6: Avg Val Loss = 0.1211 | Avg Acc = 0.9563
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_007/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.7403 | Acc: 0.4441
[Fold 0] Epoch    1 | Train Loss: 1.2534 | Val Loss: 0.7403 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1378 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1251 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1194 | Acc: 0.9569
[Fold 0] Epoch   50 | Train Loss: 0.1288 | Val Loss: 0.1200 | ES 5/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1172 | Acc: 0.9603
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1102 | Acc: 0.9609
[Fold 0] Regular checkpoint saved 

[I 2025-12-14 22:14:24,037] Trial 7 finished with value: 0.10899681496500438 and parameters: {'dropout_rate': 0.4930995614065918, 'learning_rate': 8.28969911070118e-05, 'weight_decay': 5.903130589696439e-05, 'batch_size': 64, 'h1': 224}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 152 (best Val Loss: 0.0979)
[Fold 9] Final checkpoint saved at epoch 152 - Val Loss: 0.0987 | Acc: 0.9654
Trial 7 finished in 43.14 minutes
Trial 7: Avg Val Loss = 0.1090 | Avg Acc = 0.9610
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_008/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.2480 | Acc: 0.9558
[Fold 0] Epoch    1 | Train Loss: 0.4418 | Val Loss: 0.2480 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1121 | Acc: 0.9603
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1048 | Acc: 0.9654
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.0997 | Acc: 0.9648
[Fold 0] Epoch   50 | Train Loss: 0.1169 | Val Loss: 0.0990 | ES 1/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1043 | Acc: 0.9660
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1059 | Acc: 0.9660
[Fold 0] Early stopping at epoch 7

[I 2025-12-14 22:29:42,701] Trial 8 finished with value: 0.10633577803219434 and parameters: {'dropout_rate': 0.36141528421924446, 'learning_rate': 8.178008495729147e-05, 'weight_decay': 0.0012369651517326636, 'batch_size': 16, 'h1': 224}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 76 (best Val Loss: 0.0992)
[Fold 9] Final checkpoint saved at epoch 76 - Val Loss: 0.1014 | Acc: 0.9665
Trial 8 finished in 15.31 minutes
Trial 8: Avg Val Loss = 0.1063 | Avg Acc = 0.9618
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_009/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.2887 | Acc: 0.9518
[Fold 0] Epoch    1 | Train Loss: 0.5901 | Val Loss: 0.2887 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1121 | Acc: 0.9592
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1019 | Acc: 0.9637
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1004 | Acc: 0.9654
[Fold 0] Epoch   50 | Train Loss: 0.0923 | Val Loss: 0.1027 | ES 7/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1028 | Acc: 0.9682
[Fold 0] Early stopping at epoch 73 (best Val Loss: 0.1001)
[Fold 0] Final checkpoint saved at epoch 73 - Val Loss:

[I 2025-12-14 22:42:06,077] Trial 9 finished with value: 0.1055960729518639 and parameters: {'dropout_rate': 0.4409506621780612, 'learning_rate': 0.00038215223128016003, 'weight_decay': 8.334221978967127e-06, 'batch_size': 64, 'h1': 192}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 73 (best Val Loss: 0.0932)
[Fold 9] Final checkpoint saved at epoch 73 - Val Loss: 0.0997 | Acc: 0.9671
Trial 9 finished in 12.39 minutes
Trial 9: Avg Val Loss = 0.1056 | Avg Acc = 0.9609
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_010/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1260 | Acc: 0.9586
[Fold 0] Epoch    1 | Train Loss: 0.3444 | Val Loss: 0.1260 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.0966 | Acc: 0.9648
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1029 | Acc: 0.9660
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1151 | Acc: 0.9671
[Fold 0] Epoch   50 | Train Loss: 0.0694 | Val Loss: 0.1090 | ES 26/30
[Fold 0] Early stopping at epoch 54 (best Val Loss: 0.0925)
[Fold 0] Final checkpoint saved at epoch 54 - Val Loss: 0.1187 | Acc: 0.9631
Fold 1: Training on cpu (binary classifier, BCELoss)
Che

[I 2025-12-14 22:47:39,108] Trial 10 finished with value: 0.10304188458119876 and parameters: {'dropout_rate': 0.3748365947637252, 'learning_rate': 0.000976881434149681, 'weight_decay': 1.178737537778136e-06, 'batch_size': 32, 'h1': 160}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 55 (best Val Loss: 0.0954)
[Fold 9] Final checkpoint saved at epoch 55 - Val Loss: 0.1181 | Acc: 0.9688
Trial 10 finished in 5.55 minutes
Trial 10: Avg Val Loss = 0.1030 | Avg Acc = 0.9613
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_011/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1239 | Acc: 0.9569
[Fold 0] Epoch    1 | Train Loss: 0.2286 | Val Loss: 0.1239 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.0958 | Acc: 0.9677
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1021 | Acc: 0.9665
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1007 | Acc: 0.9620
[Fold 0] Epoch   50 | Train Loss: 0.0719 | Val Loss: 0.1088 | ES 13/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1061 | Acc: 0.9654
[Fold 0] Early stopping at epoch 67 (best Val Loss: 0.0937)
[Fold 0] Final checkpoint saved at epoch 67 - Val Los

[I 2025-12-14 22:53:03,090] Trial 11 finished with value: 0.10320859833987236 and parameters: {'dropout_rate': 0.37660837550583737, 'learning_rate': 0.0009468749848207021, 'weight_decay': 1.0813653712810495e-06, 'batch_size': 32, 'h1': 160}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 43 (best Val Loss: 0.0965)
[Fold 9] Final checkpoint saved at epoch 43 - Val Loss: 0.1091 | Acc: 0.9694
Trial 11 finished in 5.40 minutes
Trial 11: Avg Val Loss = 0.1032 | Avg Acc = 0.9603
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_012/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1696 | Acc: 0.9558
[Fold 0] Epoch    1 | Train Loss: 0.3803 | Val Loss: 0.1696 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1018 | Acc: 0.9575
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.0972 | Acc: 0.9660
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.0966 | Acc: 0.9665
[Fold 0] Epoch   50 | Train Loss: 0.0887 | Val Loss: 0.1026 | ES 11/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1024 | Acc: 0.9665
[Fold 0] Early stopping at epoch 69 (best Val Loss: 0.0895)
[Fold 0] Final checkpoint saved at epoch 69 - Val Los

[I 2025-12-14 22:58:40,958] Trial 12 finished with value: 0.10274451818862806 and parameters: {'dropout_rate': 0.405201189338798, 'learning_rate': 0.0004589090989193289, 'weight_decay': 0.0009104715789432788, 'batch_size': 32, 'h1': 128}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 55 (best Val Loss: 0.0946)
[Fold 9] Final checkpoint saved at epoch 55 - Val Loss: 0.1034 | Acc: 0.9659
Trial 12 finished in 5.63 minutes
Trial 12: Avg Val Loss = 0.1027 | Avg Acc = 0.9606
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_013/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.3129 | Acc: 0.9546
[Fold 0] Epoch    1 | Train Loss: 0.5788 | Val Loss: 0.3129 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1110 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1037 | Acc: 0.9620
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.0996 | Acc: 0.9631
[Fold 0] Epoch   50 | Train Loss: 0.1074 | Val Loss: 0.0985 | ES 1/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.0989 | Acc: 0.9660
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1008 | Acc: 0.9677
[Fold 0] Early stopping at epoch 86

[I 2025-12-14 23:06:16,180] Trial 13 finished with value: 0.10507458035226591 and parameters: {'dropout_rate': 0.42686241331959257, 'learning_rate': 0.00022157788740357736, 'weight_decay': 0.0008864372475782571, 'batch_size': 32, 'h1': 128}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 83 (best Val Loss: 0.0952)
[Fold 9] Final checkpoint saved at epoch 83 - Val Loss: 0.1013 | Acc: 0.9682
Trial 13 finished in 7.59 minutes
Trial 13: Avg Val Loss = 0.1051 | Avg Acc = 0.9601
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_014/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1455 | Acc: 0.9575
[Fold 0] Epoch    1 | Train Loss: 0.3514 | Val Loss: 0.1455 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.0951 | Acc: 0.9654
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1021 | Acc: 0.9648
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1072 | Acc: 0.9648
[Fold 0] Early stopping at epoch 50 (best Val Loss: 0.0914)
[Fold 0] Final checkpoint saved at epoch 50 - Val Loss: 0.1110 | Acc: 0.9626
Fold 1: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_014/fol

[I 2025-12-14 23:10:36,866] Trial 14 finished with value: 0.10343731538385847 and parameters: {'dropout_rate': 0.20321233608087308, 'learning_rate': 0.0004542475672478992, 'weight_decay': 0.006885927783271385, 'batch_size': 32, 'h1': 128}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 44 (best Val Loss: 0.0972)
[Fold 9] Final checkpoint saved at epoch 44 - Val Loss: 0.1228 | Acc: 0.9694
Trial 14 finished in 4.34 minutes
Trial 14: Avg Val Loss = 0.1034 | Avg Acc = 0.9616
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_015/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.5664 | Acc: 0.8463
[Fold 0] Epoch    1 | Train Loss: 0.6934 | Val Loss: 0.5664 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1531 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1266 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1217 | Acc: 0.9563
[Fold 0] Epoch   50 | Train Loss: 0.1545 | Val Loss: 0.1193 | ES 4/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1134 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1126 | Acc: 0.9563
[Fold 0] Regular checkpoint saved a

[I 2025-12-14 23:29:26,440] Trial 15 finished with value: 0.10889602776665663 and parameters: {'dropout_rate': 0.4777829125515395, 'learning_rate': 3.877633950977717e-05, 'weight_decay': 0.00035630307037060727, 'batch_size': 32, 'h1': 128}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 170 (best Val Loss: 0.1007)
[Fold 9] Final checkpoint saved at epoch 170 - Val Loss: 0.1024 | Acc: 0.9625
Trial 15 finished in 18.83 minutes
Trial 15: Avg Val Loss = 0.1089 | Avg Acc = 0.9570
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_016/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1989 | Acc: 0.9535
[Fold 0] Epoch    1 | Train Loss: 0.3096 | Val Loss: 0.1989 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1068 | Acc: 0.9626
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1006 | Acc: 0.9654
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.0932 | Acc: 0.9626
[Fold 0] Epoch   50 | Train Loss: 0.0968 | Val Loss: 0.0949 | ES 3/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.0962 | Acc: 0.9637
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.0980 | Acc: 0.9626
[Fold 0] Early stopping at epoch

[I 2025-12-14 23:51:25,705] Trial 16 finished with value: 0.10325304357211931 and parameters: {'dropout_rate': 0.4032670383246012, 'learning_rate': 0.00015237479198589696, 'weight_decay': 0.00663840310976142, 'batch_size': 32, 'h1': 256}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 86 (best Val Loss: 0.0969)
[Fold 9] Final checkpoint saved at epoch 86 - Val Loss: 0.1027 | Acc: 0.9659
Trial 16 finished in 21.99 minutes
Trial 16: Avg Val Loss = 0.1033 | Avg Acc = 0.9609
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_017/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1963 | Acc: 0.9563
[Fold 0] Epoch    1 | Train Loss: 0.4147 | Val Loss: 0.1963 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1046 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.0983 | Acc: 0.9631
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1043 | Acc: 0.9643
[Fold 0] Epoch   50 | Train Loss: 0.0996 | Val Loss: 0.1012 | ES 9/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1023 | Acc: 0.9677
[Fold 0] Early stopping at epoch 71 (best Val Loss: 0.0952)
[Fold 0] Final checkpoint saved at epoch 71 - Val Los

[I 2025-12-14 23:56:06,776] Trial 17 finished with value: 0.1062323185956692 and parameters: {'dropout_rate': 0.33571243573752196, 'learning_rate': 0.000525672056360664, 'weight_decay': 0.00017086942303874665, 'batch_size': 32, 'h1': 64}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 58 (best Val Loss: 0.0960)
[Fold 9] Final checkpoint saved at epoch 58 - Val Loss: 0.1060 | Acc: 0.9665
Trial 17 finished in 4.68 minutes
Trial 17: Avg Val Loss = 0.1062 | Avg Acc = 0.9609
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_018/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1470 | Acc: 0.9563
[Fold 0] Epoch    1 | Train Loss: 0.3791 | Val Loss: 0.1470 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1119 | Acc: 0.9563
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1102 | Acc: 0.9620
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1032 | Acc: 0.9665
[Fold 0] Epoch   50 | Train Loss: 0.1134 | Val Loss: 0.0953 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.0984 | Acc: 0.9682
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1015 | Acc: 0.9677
[Fold 0] Early stopping at epoch 83

[I 2025-12-15 00:05:41,316] Trial 18 finished with value: 0.1079713560896847 and parameters: {'dropout_rate': 0.45511267002382844, 'learning_rate': 0.0003065066117325165, 'weight_decay': 0.001470474548465756, 'batch_size': 16, 'h1': 128}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 72 (best Val Loss: 0.1008)
[Fold 9] Final checkpoint saved at epoch 72 - Val Loss: 0.1061 | Acc: 0.9677
Trial 18 finished in 9.58 minutes
Trial 18: Avg Val Loss = 0.1080 | Avg Acc = 0.9605
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: checkpoints_binary_classifier/trial_019/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.5597 | Acc: 0.8417
[Fold 0] Epoch    1 | Train Loss: 0.7167 | Val Loss: 0.5597 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1279 | Acc: 0.9580
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1126 | Acc: 0.9614
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1071 | Acc: 0.9631
[Fold 0] Epoch   50 | Train Loss: 0.1238 | Val Loss: 0.1059 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 60 - Val Loss: 0.1066 | Acc: 0.9648
[Fold 0] Regular checkpoint saved at epoch 75 - Val Loss: 0.1021 | Acc: 0.9631
[Fold 0] Regular checkpoint saved a

[I 2025-12-15 00:49:00,189] Trial 19 finished with value: 0.1055841561096843 and parameters: {'dropout_rate': 0.40230166674552553, 'learning_rate': 4.6252506544895544e-05, 'weight_decay': 0.00039430985399631574, 'batch_size': 32, 'h1': 224}. Best is trial 1 with value: 0.10249554413374946.


[Fold 9] Early stopping at epoch 151 (best Val Loss: 0.0958)
[Fold 9] Final checkpoint saved at epoch 151 - Val Loss: 0.0961 | Acc: 0.9654
Trial 19 finished in 43.31 minutes
Trial 19: Avg Val Loss = 0.1056 | Avg Acc = 0.9609
{'dropout_rate': 0.40868398377036486, 'learning_rate': 0.0006993877326082944, 'weight_decay': 3.222453491315206e-05, 'batch_size': 32, 'h1': 224}


In [9]:
print("Best Trial Number:", study.best_trial.number)
print(best_params)

Best Trial Number: 1
{'dropout_rate': 0.40868398377036486, 'learning_rate': 0.0006993877326082944, 'weight_decay': 3.222453491315206e-05, 'batch_size': 32, 'h1': 224}


In [10]:
from pathlib import Path
import torch
import pandas as pd

# BASE and artifacts_dir should already be defined (same script as before)
BASE = Path.cwd()  # transfer_learning
artifacts_dir = BASE / "artifacts"

# ---------- Directories for final best models + checkpoints ----------
best_models_dir = artifacts_dir / "binary_best_models"
best_models_dir.mkdir(parents=True, exist_ok=True)

final_ckpt_dir = BASE / "checkpoints_binary_best"
final_ckpt_dir.mkdir(parents=True, exist_ok=True)

print("Best hyperparameters from Optuna:", best_params)

# Helper to derive hidden layers from best_params (same logic as in objective)
def build_hidden_layers_from_best(best_params):
    h1 = best_params["h1"]
    h2 = max(h1 // 2, 4)
    h3 = max(h2 // 2, 2)
    return [h1, h2, h3]

hidden_layers = build_hidden_layers_from_best(best_params)
dropout_rate  = best_params["dropout_rate"]
learning_rate = best_params["learning_rate"]
weight_decay  = best_params["weight_decay"]
batch_size    = best_params["batch_size"]

print("Using hidden_layers:", hidden_layers)
print("dropout:", dropout_rate, "| lr:", learning_rate, "| wd:", weight_decay, "| batch_size:", batch_size)

final_fold_metrics = []

# ---------- Final training loop for all folds (using `folds`, X, y) ----------
# Assumes you already defined:
#   X, y, folds = [(tr_idx, val_idx), ...] earlier (same as in `objective`)
for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\n==================== Final training for fold {fold_idx} ====================")

    X_train_scaled = X[tr_idx]
    y_train        = y[tr_idx]
    X_val_scaled   = X[val_idx]
    y_val          = y[val_idx]

    # Train this fold with the best hyperparameters
    best_val_loss, acc, model, train_losses, val_losses, stop_epoch = evaluate_fold(
        trial=None,
        fold_idx=fold_idx,
        X_train_scaled=X_train_scaled,
        y_train=y_train,
        X_val_scaled=X_val_scaled,
        y_val=y_val,
        hidden_layers=hidden_layers,
        learning_rate=learning_rate,
        batch_size=batch_size,
        dropout_rate=dropout_rate,
        weight_decay=weight_decay,
        max_epochs=10**9,
        patience=30,
        min_delta=0.0,
        save_checkpoints=True,
        checkpoint_dir=final_ckpt_dir,   # evaluate_fold will make fold_{k}/ inside
        save_every_n_epochs=15,
    )

    # ---------- Save the final (best) model for this fold ----------
    model_path = best_models_dir / f"binary_best_fold_{fold_idx}.pt"
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "hidden_layers": hidden_layers,
            "dropout_rate": dropout_rate,
            "learning_rate": learning_rate,
            "weight_decay": weight_decay,
            "batch_size": batch_size,
            "fold_idx": fold_idx,
            "best_val_bce": float(best_val_loss),
            "val_accuracy": float(acc),
        },
        model_path,
    )
    print(f"[Fold {fold_idx}] Saved best classifier model to: {model_path}")
    print(f"[Fold {fold_idx}] Val BCE: {best_val_loss:.4f} | Val Acc: {acc:.4f} | Stop epoch: {stop_epoch}")

    # store metrics
    final_fold_metrics.append(
        {
            "Fold": fold_idx,
            "Best_Val_BCE": float(best_val_loss),
            "Val_Accuracy": float(acc),
            "Stop_Epoch": stop_epoch,
            "Model_Path": str(model_path),
        }
    )

# ---------- Save a summary CSV of all folds ----------
metrics_df = pd.DataFrame(final_fold_metrics)
metrics_path = best_models_dir / "binary_best_models_summary.csv"
metrics_df.to_csv(metrics_path, index=False)
print("\n✅ Saved summary of best classifier models across folds to:", metrics_path)
print(metrics_df)


Best hyperparameters from Optuna: {'dropout_rate': 0.40868398377036486, 'learning_rate': 0.0006993877326082944, 'weight_decay': 3.222453491315206e-05, 'batch_size': 32, 'h1': 224}
Using hidden_layers: [224, 112, 56]
dropout: 0.40868398377036486 | lr: 0.0006993877326082944 | wd: 3.222453491315206e-05 | batch_size: 32

==================== Final training for fold 0 ====================
Fold 0: Training on cpu (binary classifier, BCELoss)
Checkpoints will be saved to: /Users/sdl5_mp/Documents/GitHub/SDL5_MP/transfer_learning/checkpoints_binary_best/fold_0
[Fold 0] Regular checkpoint saved at epoch 1 - Val Loss: 0.1264 | Acc: 0.9552
[Fold 0] Epoch    1 | Train Loss: 0.2700 | Val Loss: 0.1264 | ES 0/30
[Fold 0] Regular checkpoint saved at epoch 15 - Val Loss: 0.1018 | Acc: 0.9614
[Fold 0] Regular checkpoint saved at epoch 30 - Val Loss: 0.1082 | Acc: 0.9637
[Fold 0] Regular checkpoint saved at epoch 45 - Val Loss: 0.1089 | Acc: 0.9648
[Fold 0] Epoch   50 | Train Loss: 0.0688 | Val Loss: 0.1

In [11]:
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import confusion_matrix
from scipy.special import expit

confusion_matrices = []

for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\n===== Confusion matrix for fold {fold_idx} =====")

    # Load validation data
    X_val = X[val_idx]
    y_val = y[val_idx].astype(int)

    X_val_tensor = torch.tensor(X_val, dtype=torch.float32)

    # Load best model
    model_path = best_models_dir / f"binary_best_fold_{fold_idx}.pt"
    checkpoint = torch.load(model_path, map_location="cpu")

    model = BinaryClassifier(
        input_size=X.shape[1],
        hidden_layers=checkpoint["hidden_layers"],
        dropout_rate=checkpoint["dropout_rate"],
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    # Predict
    with torch.no_grad():
        logits = model(X_val_tensor).cpu().numpy()

    probs = expit(logits)
    preds = (probs >= 0.5).astype(int)

    # Confusion matrix
    cm = confusion_matrix(y_val, preds, labels=[0, 1])
    confusion_matrices.append(cm)

    print("Confusion matrix (rows=true, cols=pred):")
    print(cm)

    tn, fp, fn, tp = cm.ravel()
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")




===== Confusion matrix for fold 0 =====
Confusion matrix (rows=true, cols=pred):
[[1671   15]
 [  47   30]]
TN=1671, FP=15, FN=47, TP=30

===== Confusion matrix for fold 1 =====
Confusion matrix (rows=true, cols=pred):
[[1682   11]
 [  53   17]]
TN=1682, FP=11, FN=53, TP=17

===== Confusion matrix for fold 2 =====
Confusion matrix (rows=true, cols=pred):
[[1657   28]
 [  40   38]]
TN=1657, FP=28, FN=40, TP=38

===== Confusion matrix for fold 3 =====
Confusion matrix (rows=true, cols=pred):
[[1683   18]
 [  43   19]]
TN=1683, FP=18, FN=43, TP=19

===== Confusion matrix for fold 4 =====
Confusion matrix (rows=true, cols=pred):
[[1662   12]
 [  60   29]]
TN=1662, FP=12, FN=60, TP=29

===== Confusion matrix for fold 5 =====
Confusion matrix (rows=true, cols=pred):
[[1675   12]
 [  58   17]]
TN=1675, FP=12, FN=58, TP=17

===== Confusion matrix for fold 6 =====
Confusion matrix (rows=true, cols=pred):
[[1633   28]
 [  60   41]]
TN=1633, FP=28, FN=60, TP=41

===== Confusion matrix for fold 7

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_18417/2467034275.py:20: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(model_path, map_loca

In [12]:
mean_cm = np.mean(confusion_matrices, axis=0)

mean_cm_df = pd.DataFrame(
    mean_cm,
    index=["True Low&Int", "True High"],
    columns=["Pred Low&Int", "Pred High"],
)

print("\n===== Mean confusion matrix across folds =====")
print(mean_cm_df)

# Save to CSV
mean_cm_path = best_models_dir / "binary_mean_confusion_matrix.csv"
mean_cm_df.to_csv(mean_cm_path)
print(f"\n✅ Saved mean confusion matrix to: {mean_cm_path}")



===== Mean confusion matrix across folds =====
              Pred Low&Int  Pred High
True Low&Int        1669.2       16.1
True High             51.8       25.4

✅ Saved mean confusion matrix to: /Users/sdl5_mp/Documents/GitHub/SDL5_MP/transfer_learning/artifacts/binary_best_models/binary_mean_confusion_matrix.csv


In [13]:
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import confusion_matrix
from scipy.special import expit  # stable sigmoid

def metrics_from_confusion(cm):
    """
    cm = [[TN, FP],
          [FN, TP]]
    """
    TN, FP, FN, TP = cm.ravel()

    accuracy  = (TP + TN) / (TP + TN + FP + FN)
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1        = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    specificity = TN / (TN + FP) if (TN + FP) > 0 else 0.0

    return {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Specificity": specificity,
    }

all_fold_metrics = []
all_conf_matrices = []

for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\nEvaluating fold {fold_idx}")

    # Load best model for this fold
    ckpt = torch.load(best_models_dir / f"binary_best_fold_{fold_idx}.pt", map_location="cpu")

    model = BinaryClassifier(
        input_size=X.shape[1],
        hidden_layers=ckpt["hidden_layers"],
        dropout_rate=ckpt["dropout_rate"],
    )
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    # Validation data
    X_val = torch.tensor(X[val_idx], dtype=torch.float32)
    y_val = y[val_idx].astype(int)

    # Predict
    with torch.no_grad():
        logits = model(X_val).numpy()

    probs = expit(logits)
    preds = (probs >= 0.5).astype(int)

    # Confusion matrix: [[TN, FP], [FN, TP]]
    cm = confusion_matrix(y_val, preds)
    all_conf_matrices.append(cm)

    # Metrics
    metrics = metrics_from_confusion(cm)
    metrics["Fold"] = fold_idx
    all_fold_metrics.append(metrics)

    print("Confusion matrix:\n", cm)
    print(metrics)



Evaluating fold 0
Confusion matrix:
 [[1671   15]
 [  47   30]]
{'Accuracy': np.float64(0.9648326715825298), 'Precision': np.float64(0.6666666666666666), 'Recall': np.float64(0.38961038961038963), 'F1': np.float64(0.4918032786885245), 'Specificity': np.float64(0.9911032028469751), 'Fold': 0}

Evaluating fold 1
Confusion matrix:
 [[1682   11]
 [  53   17]]
{'Accuracy': np.float64(0.9636982416335791), 'Precision': np.float64(0.6071428571428571), 'Recall': np.float64(0.24285714285714285), 'F1': np.float64(0.3469387755102041), 'Specificity': np.float64(0.993502658003544), 'Fold': 1}

Evaluating fold 2
Confusion matrix:
 [[1657   28]
 [  40   38]]
{'Accuracy': np.float64(0.9614293817356778), 'Precision': np.float64(0.5757575757575758), 'Recall': np.float64(0.48717948717948717), 'F1': np.float64(0.5277777777777778), 'Specificity': np.float64(0.9833827893175074), 'Fold': 2}

Evaluating fold 3
Confusion matrix:
 [[1683   18]
 [  43   19]]
{'Accuracy': np.float64(0.9653998865570051), 'Precisio

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_18417/1914565896.py:35: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(best_models_dir / f"binary

In [14]:
metrics_df = pd.DataFrame(all_fold_metrics)

mean_metrics = metrics_df.mean(numeric_only=True)
std_metrics  = metrics_df.std(numeric_only=True)

summary_df = pd.DataFrame({
    "Mean": mean_metrics,
    "Std": std_metrics
})

print("\n=== Cross-validated performance ===")
print(summary_df)

summary_df.to_csv(
    best_models_dir / "binary_classifier_confusion_metrics_summary.csv"
)



=== Cross-validated performance ===
                 Mean       Std
Accuracy     0.961475  0.004648
Precision    0.621636  0.080951
Recall       0.324801  0.085421
F1           0.417997  0.068191
Specificity  0.990437  0.004555
Fold         4.500000  3.027650
