In [1]:
# pip install xgboost scikit-learn

import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

def build_xgboost_binary_classifier(
    n_estimators: int = 800,
    learning_rate: float = 0.05,
    max_depth: int = 5,
    subsample: float = 0.8,
    colsample_bytree: float = 0.8,
    reg_lambda: float = 1.0,
    reg_alpha: float = 0.0,
    min_child_weight: float = 1.0,
    gamma: float = 0.0,
    random_state: int = 42,
    n_jobs: int = -1,
):
    """
    Replacement for your PyTorch BinaryClassifier:
    Returns an XGBoost binary classifier (sklearn API).
    """
    model = XGBClassifier(
        objective="binary:logistic",   # outputs probabilities via sigmoid
        eval_metric="logloss",         # avoid warning; can also use "auc"
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        min_child_weight=min_child_weight,
        gamma=gamma,
        random_state=random_state,
        n_jobs=n_jobs,
        tree_method="hist",            # fast + good default on CPU
    )
    return model

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold

# 0) Load ALREADY-SCALED binary dataset
df_binary = pd.read_csv("artifacts/final_train_scaled_binary_clustered.csv")

TARGET_COL = "MP_binary_high"

exclude = {"SMILES", TARGET_COL, "MW", "MP", "MP_category_default", "Structure_Cluster"}

num_cols = df_binary.select_dtypes(include=[np.number]).columns
feature_cols = [c for c in num_cols if c not in exclude]

# ---- NEW: load selected feature names (produced by your RFE step) ----
selected_feature_names = pd.read_csv("selected_rdkit_features.csv", header=None)[0].tolist()

# Keep only selected features that exist in this dataframe (safety)
selected_feature_names = [c for c in selected_feature_names if c in feature_cols]

# Build reduced X/y
X = df_binary[selected_feature_names].to_numpy(np.float32)
y = df_binary[TARGET_COL].to_numpy(np.int32) 

# Stratification labels (cluster)
y_strat = df_binary["Structure_Cluster"].astype(str).to_numpy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("n features:", len(selected_feature_names))
print("Label counts:", dict(zip(*np.unique(y, return_counts=True))))

# 1) Fix folds once (same)
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
folds = [(tr_idx, val_idx) for tr_idx, val_idx in skf.split(X, y_strat)]
print("Built folds:", len(folds))

X shape: (17625, 20)
y shape: (17625,)
n features: 20
Label counts: {np.int32(0): np.int64(16853), np.int32(1): np.int64(772)}
Built folds: 10


In [5]:
import numpy as np
import pandas as pd
from pathlib import Path

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score
import joblib


def evaluate_fold_xgb(
    fold_idx,
    X_train,
    y_train,
    X_val,
    y_val,
    params,
    save_checkpoints=True,
    checkpoint_dir="checkpoints_xgb_classifier",
):
    y_train = np.asarray(y_train).astype(int)
    y_val   = np.asarray(y_val).astype(int)

    # imbalance knob: neg/pos (train fold only)
    pos = y_train.sum()
    neg = y_train.size - pos
    scale_pos_weight = float(neg / (pos + 1e-12))

    model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="auc",
    early_stopping_rounds=50,   # <-- HERE
    tree_method="hist",
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight,
    **params,
)

    model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=False,
)


    probs = model.predict_proba(X_val)[:, 1]
    preds = (probs >= 0.5).astype(int)

    auc = roc_auc_score(y_val, probs)
    val_loss = log_loss(y_val, probs, labels=[0, 1])
    acc = accuracy_score(y_val, preds)

    best_iter = getattr(model, "best_iteration", None)

    if save_checkpoints:
        ckpt_root = Path(checkpoint_dir) / f"fold_{fold_idx}"
        ckpt_root.mkdir(parents=True, exist_ok=True)

        # Avoid overwriting: include fold in filename
        joblib.dump(model, ckpt_root / f"xgb_model_fold_{fold_idx}.joblib")

        pd.DataFrame([{
            "fold": fold_idx,
            "val_auc": float(auc),
            "val_logloss": float(val_loss),
            "accuracy@0.5": float(acc),
            "best_iteration": best_iter,
            "scale_pos_weight": scale_pos_weight,
        }]).to_csv(ckpt_root / f"metrics_fold_{fold_idx}.csv", index=False)

    print(
        f"[Fold {fold_idx}] AUC: {auc:.4f} | Logloss: {val_loss:.4f} | Acc@0.5: {acc:.4f} | best_iter: {best_iter}"
    )
    return float(auc), float(val_loss), float(acc), model, best_iter


import optuna

def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 3000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 20.0, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "gamma": trial.suggest_float("gamma", 0.0, 5.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 50.0, log=True),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-6, 10.0, log=True),
    }

    aucs, losses, accs = [], [], []

    for fold_idx, (tr_idx, val_idx) in enumerate(folds):
        X_train = X[tr_idx]
        y_train = y[tr_idx]
        X_val   = X[val_idx]
        y_val   = y[val_idx]

        trial_checkpoint_root = Path("checkpoints_xgb_classifier") / f"trial_{trial.number:03d}"

        auc, val_loss, acc, _, _ = evaluate_fold_xgb(
            fold_idx=fold_idx,
            X_train=X_train,
            y_train=y_train,
            X_val=X_val,
            y_val=y_val,
            params=params,
            save_checkpoints=True,
            checkpoint_dir=trial_checkpoint_root,
        )

        aucs.append(auc)
        losses.append(val_loss)
        accs.append(acc)

    avg_auc = float(np.mean(aucs))
    avg_loss = float(np.mean(losses))
    avg_acc = float(np.mean(accs))

    print(
        f"Trial {trial.number}: Avg AUC={avg_auc:.4f} | Avg Logloss={avg_loss:.4f} | Avg Acc@0.5={avg_acc:.4f}"
    )

    # Optuna maximizes AUC (recommended)
    return avg_auc


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=20)

print("Best params:", study.best_params)
print("Best value (AUC):", study.best_value)


[I 2026-01-19 03:01:10,756] A new study created in memory with name: no-name-73c835d0-6174-4b23-818f-43dcfdf02be3


[Fold 0] AUC: 0.9439 | Logloss: 0.2478 | Acc@0.5: 0.8860 | best_iter: 917
[Fold 1] AUC: 0.9425 | Logloss: 0.2740 | Acc@0.5: 0.8729 | best_iter: 657
[Fold 2] AUC: 0.9286 | Logloss: 0.3505 | Acc@0.5: 0.8395 | best_iter: 167
[Fold 3] AUC: 0.9172 | Logloss: 0.3320 | Acc@0.5: 0.8565 | best_iter: 195
[Fold 4] AUC: 0.9197 | Logloss: 0.2944 | Acc@0.5: 0.8707 | best_iter: 362
[Fold 5] AUC: 0.9370 | Logloss: 0.2526 | Acc@0.5: 0.8848 | best_iter: 1014
[Fold 6] AUC: 0.9365 | Logloss: 0.2490 | Acc@0.5: 0.8944 | best_iter: 1140
[Fold 7] AUC: 0.9283 | Logloss: 0.3096 | Acc@0.5: 0.8536 | best_iter: 380
[Fold 8] AUC: 0.9310 | Logloss: 0.3315 | Acc@0.5: 0.8479 | best_iter: 226


[I 2026-01-19 03:01:18,004] Trial 0 finished with value: 0.9304262703871873 and parameters: {'n_estimators': 2324, 'learning_rate': 0.020894160431898266, 'max_depth': 4, 'min_child_weight': 15.125605441002925, 'subsample': 0.9767017405354007, 'colsample_bytree': 0.5513760480397957, 'gamma': 3.8487550297691757, 'reg_lambda': 0.005270803920141563, 'reg_alpha': 9.610510663679555e-05}. Best is trial 0 with value: 0.9304262703871873.


[Fold 9] AUC: 0.9195 | Logloss: 0.3207 | Acc@0.5: 0.8575 | best_iter: 248
Trial 0: Avg AUC=0.9304 | Avg Logloss=0.2962 | Avg Acc@0.5=0.8664
[Fold 0] AUC: 0.9529 | Logloss: 0.1704 | Acc@0.5: 0.9280 | best_iter: 366
[Fold 1] AUC: 0.9462 | Logloss: 0.2249 | Acc@0.5: 0.9019 | best_iter: 142
[Fold 2] AUC: 0.9374 | Logloss: 0.2708 | Acc@0.5: 0.8809 | best_iter: 64
[Fold 3] AUC: 0.9247 | Logloss: 0.2519 | Acc@0.5: 0.8928 | best_iter: 85
[Fold 4] AUC: 0.9250 | Logloss: 0.2304 | Acc@0.5: 0.9075 | best_iter: 114
[Fold 5] AUC: 0.9353 | Logloss: 0.2572 | Acc@0.5: 0.8814 | best_iter: 93
[Fold 6] AUC: 0.9401 | Logloss: 0.2138 | Acc@0.5: 0.9154 | best_iter: 217
[Fold 7] AUC: 0.9316 | Logloss: 0.2661 | Acc@0.5: 0.8774 | best_iter: 76
[Fold 8] AUC: 0.9378 | Logloss: 0.2552 | Acc@0.5: 0.8871 | best_iter: 88


[I 2026-01-19 03:01:21,255] Trial 1 finished with value: 0.9350527433024215 and parameters: {'n_estimators': 878, 'learning_rate': 0.07040711531516214, 'max_depth': 6, 'min_child_weight': 18.471811247133786, 'subsample': 0.5474768103642326, 'colsample_bytree': 0.589522390675819, 'gamma': 4.221704429442791, 'reg_lambda': 0.002270356976819487, 'reg_alpha': 1.7713127648232698}. Best is trial 1 with value: 0.9350527433024215.


[Fold 9] AUC: 0.9196 | Logloss: 0.2557 | Acc@0.5: 0.8876 | best_iter: 87
Trial 1: Avg AUC=0.9351 | Avg Logloss=0.2396 | Avg Acc@0.5=0.8960
[Fold 0] AUC: 0.9437 | Logloss: 0.2630 | Acc@0.5: 0.8820 | best_iter: 452
[Fold 1] AUC: 0.9392 | Logloss: 0.2980 | Acc@0.5: 0.8599 | best_iter: 282
[Fold 2] AUC: 0.9270 | Logloss: 0.3166 | Acc@0.5: 0.8480 | best_iter: 228
[Fold 3] AUC: 0.9170 | Logloss: 0.2821 | Acc@0.5: 0.8752 | best_iter: 321
[Fold 4] AUC: 0.9180 | Logloss: 0.3089 | Acc@0.5: 0.8559 | best_iter: 179
[Fold 5] AUC: 0.9269 | Logloss: 0.3208 | Acc@0.5: 0.8490 | best_iter: 206
[Fold 6] AUC: 0.9333 | Logloss: 0.2759 | Acc@0.5: 0.8808 | best_iter: 442
[Fold 7] AUC: 0.9222 | Logloss: 0.3288 | Acc@0.5: 0.8445 | best_iter: 189
[Fold 8] AUC: 0.9268 | Logloss: 0.3294 | Acc@0.5: 0.8462 | best_iter: 162


[I 2026-01-19 03:01:24,800] Trial 2 finished with value: 0.9272585381296974 and parameters: {'n_estimators': 1458, 'learning_rate': 0.05778067472736423, 'max_depth': 3, 'min_child_weight': 4.457580375411172, 'subsample': 0.6436967980210144, 'colsample_bytree': 0.7435232839817243, 'gamma': 0.8162662251614472, 'reg_lambda': 7.548016927391667, 'reg_alpha': 0.7060617074315111}. Best is trial 1 with value: 0.9350527433024215.


[Fold 9] AUC: 0.9184 | Logloss: 0.3295 | Acc@0.5: 0.8485 | best_iter: 144
Trial 2: Avg AUC=0.9273 | Avg Logloss=0.3053 | Avg Acc@0.5=0.8590
[Fold 0] AUC: 0.9484 | Logloss: 0.1805 | Acc@0.5: 0.9251 | best_iter: 222
[Fold 1] AUC: 0.9397 | Logloss: 0.1719 | Acc@0.5: 0.9348 | best_iter: 297
[Fold 2] AUC: 0.9246 | Logloss: 0.2905 | Acc@0.5: 0.8673 | best_iter: 62
[Fold 3] AUC: 0.9093 | Logloss: 0.3076 | Acc@0.5: 0.8548 | best_iter: 42
[Fold 4] AUC: 0.9222 | Logloss: 0.2676 | Acc@0.5: 0.8832 | best_iter: 68
[Fold 5] AUC: 0.9379 | Logloss: 0.2127 | Acc@0.5: 0.9001 | best_iter: 187
[Fold 6] AUC: 0.9325 | Logloss: 0.2636 | Acc@0.5: 0.8854 | best_iter: 95
[Fold 7] AUC: 0.9303 | Logloss: 0.2475 | Acc@0.5: 0.8899 | best_iter: 118
[Fold 8] AUC: 0.9286 | Logloss: 0.3291 | Acc@0.5: 0.8473 | best_iter: 28


[I 2026-01-19 03:01:27,510] Trial 3 finished with value: 0.9293145789568118 and parameters: {'n_estimators': 2450, 'learning_rate': 0.13582456293271514, 'max_depth': 4, 'min_child_weight': 1.0143550417738598, 'subsample': 0.6246833459239111, 'colsample_bytree': 0.835689687621981, 'gamma': 2.379382418366289, 'reg_lambda': 0.03891501475350636, 'reg_alpha': 0.6589055091928617}. Best is trial 1 with value: 0.9350527433024215.


[Fold 9] AUC: 0.9198 | Logloss: 0.2668 | Acc@0.5: 0.8797 | best_iter: 79
Trial 3: Avg AUC=0.9293 | Avg Logloss=0.2538 | Avg Acc@0.5=0.8867
[Fold 0] AUC: 0.9367 | Logloss: 0.2930 | Acc@0.5: 0.8650 | best_iter: 373
[Fold 1] AUC: 0.9361 | Logloss: 0.3132 | Acc@0.5: 0.8548 | best_iter: 292
[Fold 2] AUC: 0.9257 | Logloss: 0.3191 | Acc@0.5: 0.8457 | best_iter: 288
[Fold 3] AUC: 0.9122 | Logloss: 0.2974 | Acc@0.5: 0.8627 | best_iter: 348
[Fold 4] AUC: 0.9194 | Logloss: 0.2959 | Acc@0.5: 0.8684 | best_iter: 339
[Fold 5] AUC: 0.9322 | Logloss: 0.2694 | Acc@0.5: 0.8774 | best_iter: 654
[Fold 6] AUC: 0.9337 | Logloss: 0.2644 | Acc@0.5: 0.8837 | best_iter: 648
[Fold 7] AUC: 0.9255 | Logloss: 0.2950 | Acc@0.5: 0.8621 | best_iter: 441
[Fold 8] AUC: 0.9293 | Logloss: 0.3396 | Acc@0.5: 0.8405 | best_iter: 175


[I 2026-01-19 03:01:31,832] Trial 4 finished with value: 0.9266361958622129 and parameters: {'n_estimators': 655, 'learning_rate': 0.04090068454686792, 'max_depth': 3, 'min_child_weight': 1.7441484775702878, 'subsample': 0.7965988057975384, 'colsample_bytree': 0.7841924527213631, 'gamma': 0.6424608321283864, 'reg_lambda': 0.0012250330499108872, 'reg_alpha': 0.1340093159615365}. Best is trial 1 with value: 0.9350527433024215.


[Fold 9] AUC: 0.9156 | Logloss: 0.3380 | Acc@0.5: 0.8422 | best_iter: 166
Trial 4: Avg AUC=0.9266 | Avg Logloss=0.3025 | Avg Acc@0.5=0.8603
[Fold 0] AUC: 0.9446 | Logloss: 0.2225 | Acc@0.5: 0.8996 | best_iter: 255
[Fold 1] AUC: 0.9364 | Logloss: 0.2644 | Acc@0.5: 0.8701 | best_iter: 155
[Fold 2] AUC: 0.9259 | Logloss: 0.2763 | Acc@0.5: 0.8758 | best_iter: 141
[Fold 3] AUC: 0.9118 | Logloss: 0.2995 | Acc@0.5: 0.8605 | best_iter: 83
[Fold 4] AUC: 0.9211 | Logloss: 0.3279 | Acc@0.5: 0.8457 | best_iter: 38
[Fold 5] AUC: 0.9278 | Logloss: 0.3251 | Acc@0.5: 0.8417 | best_iter: 58
[Fold 6] AUC: 0.9357 | Logloss: 0.2279 | Acc@0.5: 0.9041 | best_iter: 277
[Fold 7] AUC: 0.9288 | Logloss: 0.2649 | Acc@0.5: 0.8780 | best_iter: 165
[Fold 8] AUC: 0.9264 | Logloss: 0.3410 | Acc@0.5: 0.8400 | best_iter: 40


[I 2026-01-19 03:01:33,950] Trial 5 finished with value: 0.927660115075278 and parameters: {'n_estimators': 2565, 'learning_rate': 0.18949764746449999, 'max_depth': 3, 'min_child_weight': 2.081304290030191, 'subsample': 0.9013204770159555, 'colsample_bytree': 0.6704089801338586, 'gamma': 0.30989246133395376, 'reg_lambda': 0.01256241068896052, 'reg_alpha': 4.825830409232919e-05}. Best is trial 1 with value: 0.9350527433024215.


[Fold 9] AUC: 0.9181 | Logloss: 0.2973 | Acc@0.5: 0.8604 | best_iter: 90
Trial 5: Avg AUC=0.9277 | Avg Logloss=0.2847 | Avg Acc@0.5=0.8676
[Fold 0] AUC: 0.9498 | Logloss: 0.1618 | Acc@0.5: 0.9353 | best_iter: 172
[Fold 1] AUC: 0.9426 | Logloss: 0.1813 | Acc@0.5: 0.9240 | best_iter: 109
[Fold 2] AUC: 0.9382 | Logloss: 0.2239 | Acc@0.5: 0.9081 | best_iter: 47
[Fold 3] AUC: 0.9290 | Logloss: 0.2391 | Acc@0.5: 0.9024 | best_iter: 36
[Fold 4] AUC: 0.9234 | Logloss: 0.1968 | Acc@0.5: 0.9257 | best_iter: 64
[Fold 5] AUC: 0.9386 | Logloss: 0.1885 | Acc@0.5: 0.9194 | best_iter: 103
[Fold 6] AUC: 0.9401 | Logloss: 0.1796 | Acc@0.5: 0.9279 | best_iter: 201
[Fold 7] AUC: 0.9355 | Logloss: 0.2401 | Acc@0.5: 0.8950 | best_iter: 45
[Fold 8] AUC: 0.9340 | Logloss: 0.2326 | Acc@0.5: 0.8978 | best_iter: 48


[I 2026-01-19 03:01:37,213] Trial 6 finished with value: 0.9352161307271608 and parameters: {'n_estimators': 1256, 'learning_rate': 0.10747344322031677, 'max_depth': 10, 'min_child_weight': 19.31143325923978, 'subsample': 0.926904250672244, 'colsample_bytree': 0.594906874627039, 'gamma': 2.088000264906611, 'reg_lambda': 18.690294589392547, 'reg_alpha': 0.032804339459643214}. Best is trial 6 with value: 0.9352161307271608.


[Fold 9] AUC: 0.9209 | Logloss: 0.2704 | Acc@0.5: 0.8837 | best_iter: 27
Trial 6: Avg AUC=0.9352 | Avg Logloss=0.2114 | Avg Acc@0.5=0.9119
[Fold 0] AUC: 0.9498 | Logloss: 0.1506 | Acc@0.5: 0.9404 | best_iter: 548
[Fold 1] AUC: 0.9485 | Logloss: 0.1546 | Acc@0.5: 0.9348 | best_iter: 600
[Fold 2] AUC: 0.9338 | Logloss: 0.3845 | Acc@0.5: 0.9081 | best_iter: 51
[Fold 3] AUC: 0.9209 | Logloss: 0.2233 | Acc@0.5: 0.9257 | best_iter: 150
[Fold 4] AUC: 0.9198 | Logloss: 0.2287 | Acc@0.5: 0.9234 | best_iter: 142
[Fold 5] AUC: 0.9391 | Logloss: 0.1897 | Acc@0.5: 0.9200 | best_iter: 309
[Fold 6] AUC: 0.9353 | Logloss: 0.3362 | Acc@0.5: 0.9132 | best_iter: 68
[Fold 7] AUC: 0.9354 | Logloss: 0.1973 | Acc@0.5: 0.9154 | best_iter: 301
[Fold 8] AUC: 0.9353 | Logloss: 0.3782 | Acc@0.5: 0.9137 | best_iter: 52


[I 2026-01-19 03:01:44,180] Trial 7 finished with value: 0.9339393558413782 and parameters: {'n_estimators': 614, 'learning_rate': 0.015566012479128687, 'max_depth': 8, 'min_child_weight': 2.8894738269286027, 'subsample': 0.5369742277157952, 'colsample_bytree': 0.7894215037959222, 'gamma': 4.9021045210489085, 'reg_lambda': 0.0011771732739318881, 'reg_alpha': 0.0005822619523152318}. Best is trial 6 with value: 0.9352161307271608.


[Fold 9] AUC: 0.9214 | Logloss: 0.2061 | Acc@0.5: 0.9115 | best_iter: 200
Trial 7: Avg AUC=0.9339 | Avg Logloss=0.2449 | Avg Acc@0.5=0.9206
[Fold 0] AUC: 0.9525 | Logloss: 0.1692 | Acc@0.5: 0.9297 | best_iter: 117
[Fold 1] AUC: 0.9408 | Logloss: 0.1722 | Acc@0.5: 0.9257 | best_iter: 123
[Fold 2] AUC: 0.9401 | Logloss: 0.2193 | Acc@0.5: 0.9070 | best_iter: 50
[Fold 3] AUC: 0.9220 | Logloss: 0.2507 | Acc@0.5: 0.9030 | best_iter: 28
[Fold 4] AUC: 0.9233 | Logloss: 0.1894 | Acc@0.5: 0.9263 | best_iter: 75
[Fold 5] AUC: 0.9353 | Logloss: 0.1660 | Acc@0.5: 0.9336 | best_iter: 191
[Fold 6] AUC: 0.9416 | Logloss: 0.1966 | Acc@0.5: 0.9245 | best_iter: 87
[Fold 7] AUC: 0.9361 | Logloss: 0.2482 | Acc@0.5: 0.8893 | best_iter: 39
[Fold 8] AUC: 0.9337 | Logloss: 0.2304 | Acc@0.5: 0.9030 | best_iter: 42


[I 2026-01-19 03:01:47,555] Trial 8 finished with value: 0.9345631009219136 and parameters: {'n_estimators': 1449, 'learning_rate': 0.10044499006390814, 'max_depth': 9, 'min_child_weight': 8.527584117514843, 'subsample': 0.6207319795183369, 'colsample_bytree': 0.5009130193077861, 'gamma': 3.067608976985526, 'reg_lambda': 9.552814728201382, 'reg_alpha': 0.09529127175207656}. Best is trial 6 with value: 0.9352161307271608.


[Fold 9] AUC: 0.9202 | Logloss: 0.1704 | Acc@0.5: 0.9240 | best_iter: 140
Trial 8: Avg AUC=0.9346 | Avg Logloss=0.2012 | Avg Acc@0.5=0.9166
[Fold 0] AUC: 0.9444 | Logloss: 0.2585 | Acc@0.5: 0.8894 | best_iter: 795
[Fold 1] AUC: 0.9370 | Logloss: 0.3097 | Acc@0.5: 0.8548 | best_iter: 360
[Fold 2] AUC: 0.9208 | Logloss: 0.3604 | Acc@0.5: 0.8259 | best_iter: 121
[Fold 3] AUC: 0.9163 | Logloss: 0.3051 | Acc@0.5: 0.8559 | best_iter: 331
[Fold 4] AUC: 0.9186 | Logloss: 0.3022 | Acc@0.5: 0.8639 | best_iter: 341
[Fold 5] AUC: 0.9305 | Logloss: 0.2855 | Acc@0.5: 0.8683 | best_iter: 581
[Fold 6] AUC: 0.9349 | Logloss: 0.2724 | Acc@0.5: 0.8757 | best_iter: 795
[Fold 7] AUC: 0.9218 | Logloss: 0.3264 | Acc@0.5: 0.8451 | best_iter: 282
[Fold 8] AUC: 0.9296 | Logloss: 0.3325 | Acc@0.5: 0.8490 | best_iter: 208


[I 2026-01-19 03:01:52,677] Trial 9 finished with value: 0.9272147639935877 and parameters: {'n_estimators': 2183, 'learning_rate': 0.039188070001755206, 'max_depth': 3, 'min_child_weight': 4.051611241538855, 'subsample': 0.5018205363879835, 'colsample_bytree': 0.8064418287201742, 'gamma': 3.6905801416554236, 'reg_lambda': 24.64466327337127, 'reg_alpha': 0.528525925965128}. Best is trial 6 with value: 0.9352161307271608.


[Fold 9] AUC: 0.9183 | Logloss: 0.3145 | Acc@0.5: 0.8536 | best_iter: 295
Trial 9: Avg AUC=0.9272 | Avg Logloss=0.3067 | Avg Acc@0.5=0.8582
[Fold 0] AUC: 0.9507 | Logloss: 0.1311 | Acc@0.5: 0.9484 | best_iter: 502
[Fold 1] AUC: 0.9456 | Logloss: 0.1445 | Acc@0.5: 0.9433 | best_iter: 315
[Fold 2] AUC: 0.9384 | Logloss: 0.1574 | Acc@0.5: 0.9359 | best_iter: 245
[Fold 3] AUC: 0.9255 | Logloss: 0.1708 | Acc@0.5: 0.9416 | best_iter: 160
[Fold 4] AUC: 0.9208 | Logloss: 0.1469 | Acc@0.5: 0.9450 | best_iter: 387
[Fold 5] AUC: 0.9427 | Logloss: 0.1457 | Acc@0.5: 0.9421 | best_iter: 412
[Fold 6] AUC: 0.9434 | Logloss: 0.1726 | Acc@0.5: 0.9353 | best_iter: 219
[Fold 7] AUC: 0.9420 | Logloss: 0.1746 | Acc@0.5: 0.9274 | best_iter: 221
[Fold 8] AUC: 0.9363 | Logloss: 0.2205 | Acc@0.5: 0.9149 | best_iter: 96


[I 2026-01-19 03:02:02,333] Trial 10 finished with value: 0.9366294281009996 and parameters: {'n_estimators': 1162, 'learning_rate': 0.023962556929236718, 'max_depth': 10, 'min_child_weight': 8.99775502964076, 'subsample': 0.8106626806922802, 'colsample_bytree': 0.9881283795532174, 'gamma': 1.847361653297833, 'reg_lambda': 0.9569699786903291, 'reg_alpha': 2.5490266596638967e-06}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9208 | Logloss: 0.1465 | Acc@0.5: 0.9438 | best_iter: 314
Trial 10: Avg AUC=0.9366 | Avg Logloss=0.1611 | Avg Acc@0.5=0.9378
[Fold 0] AUC: 0.9415 | Logloss: 0.4706 | Acc@0.5: 0.9098 | best_iter: 44
[Fold 1] AUC: 0.9454 | Logloss: 0.1436 | Acc@0.5: 0.9427 | best_iter: 812
[Fold 2] AUC: 0.9363 | Logloss: 0.1872 | Acc@0.5: 0.9280 | best_iter: 313
[Fold 3] AUC: 0.9182 | Logloss: 0.4852 | Acc@0.5: 0.9223 | best_iter: 39
[Fold 4] AUC: 0.9180 | Logloss: 0.1656 | Acc@0.5: 0.9393 | best_iter: 485
[Fold 5] AUC: 0.9376 | Logloss: 0.2535 | Acc@0.5: 0.9166 | best_iter: 174
[Fold 6] AUC: 0.9417 | Logloss: 0.1959 | Acc@0.5: 0.9257 | best_iter: 312
[Fold 7] AUC: 0.9328 | Logloss: 0.6594 | Acc@0.5: 0.8961 | best_iter: 4
[Fold 8] AUC: 0.9383 | Logloss: 0.2758 | Acc@0.5: 0.9098 | best_iter: 148


[I 2026-01-19 03:02:11,492] Trial 11 finished with value: 0.9323045598640387 and parameters: {'n_estimators': 1029, 'learning_rate': 0.010099116113131374, 'max_depth': 10, 'min_child_weight': 9.281347046456325, 'subsample': 0.8220466741304402, 'colsample_bytree': 0.9999067076656005, 'gamma': 1.9967936719792156, 'reg_lambda': 1.0619464251101594, 'reg_alpha': 1.026084524911253e-06}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9132 | Logloss: 0.2886 | Acc@0.5: 0.9149 | best_iter: 130
Trial 11: Avg AUC=0.9323 | Avg Logloss=0.3125 | Avg Acc@0.5=0.9205
[Fold 0] AUC: 0.9465 | Logloss: 0.1364 | Acc@0.5: 0.9478 | best_iter: 374
[Fold 1] AUC: 0.9347 | Logloss: 0.5011 | Acc@0.5: 0.9075 | best_iter: 13
[Fold 2] AUC: 0.9357 | Logloss: 0.1704 | Acc@0.5: 0.9331 | best_iter: 151
[Fold 3] AUC: 0.9261 | Logloss: 0.1706 | Acc@0.5: 0.9427 | best_iter: 135
[Fold 4] AUC: 0.9057 | Logloss: 0.5689 | Acc@0.5: 0.9024 | best_iter: 7
[Fold 5] AUC: 0.9442 | Logloss: 0.1453 | Acc@0.5: 0.9404 | best_iter: 338
[Fold 6] AUC: 0.9442 | Logloss: 0.1576 | Acc@0.5: 0.9410 | best_iter: 306
[Fold 7] AUC: 0.9370 | Logloss: 0.1892 | Acc@0.5: 0.9234 | best_iter: 144
[Fold 8] AUC: 0.9380 | Logloss: 0.1678 | Acc@0.5: 0.9296 | best_iter: 206


[I 2026-01-19 03:02:18,864] Trial 12 finished with value: 0.9330958560759035 and parameters: {'n_estimators': 1873, 'learning_rate': 0.026097542874439907, 'max_depth': 10, 'min_child_weight': 9.244098647458905, 'subsample': 0.9039126026316706, 'colsample_bytree': 0.9561040455435947, 'gamma': 1.558040912857068, 'reg_lambda': 0.6846112112074707, 'reg_alpha': 0.023072850767912923}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9189 | Logloss: 0.1508 | Acc@0.5: 0.9387 | best_iter: 239
Trial 12: Avg AUC=0.9331 | Avg Logloss=0.2358 | Avg Acc@0.5=0.9307
[Fold 0] AUC: 0.9457 | Logloss: 0.1613 | Acc@0.5: 0.9314 | best_iter: 121
[Fold 1] AUC: 0.9399 | Logloss: 0.1682 | Acc@0.5: 0.9308 | best_iter: 105
[Fold 2] AUC: 0.9384 | Logloss: 0.3925 | Acc@0.5: 0.8854 | best_iter: 8
[Fold 3] AUC: 0.9306 | Logloss: 0.2173 | Acc@0.5: 0.9138 | best_iter: 35
[Fold 4] AUC: 0.9169 | Logloss: 0.1830 | Acc@0.5: 0.9331 | best_iter: 70
[Fold 5] AUC: 0.9424 | Logloss: 0.1854 | Acc@0.5: 0.9222 | best_iter: 74
[Fold 6] AUC: 0.9436 | Logloss: 0.1846 | Acc@0.5: 0.9268 | best_iter: 96
[Fold 7] AUC: 0.9372 | Logloss: 0.2313 | Acc@0.5: 0.8984 | best_iter: 41
[Fold 8] AUC: 0.9388 | Logloss: 0.2363 | Acc@0.5: 0.8984 | best_iter: 31


[I 2026-01-19 03:02:21,807] Trial 13 finished with value: 0.9356929917598679 and parameters: {'n_estimators': 1168, 'learning_rate': 0.09561117282322025, 'max_depth': 8, 'min_child_weight': 12.386249013250476, 'subsample': 0.7384143051856118, 'colsample_bytree': 0.8989016085093606, 'gamma': 1.5142921152917617, 'reg_lambda': 2.103687296683133, 'reg_alpha': 0.0047122289337942535}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9235 | Logloss: 0.1555 | Acc@0.5: 0.9347 | best_iter: 140
Trial 13: Avg AUC=0.9357 | Avg Logloss=0.2115 | Avg Acc@0.5=0.9175
[Fold 0] AUC: 0.9441 | Logloss: 0.2168 | Acc@0.5: 0.9030 | best_iter: 139
[Fold 1] AUC: 0.9471 | Logloss: 0.1554 | Acc@0.5: 0.9399 | best_iter: 419
[Fold 2] AUC: 0.9367 | Logloss: 0.2428 | Acc@0.5: 0.9002 | best_iter: 98
[Fold 3] AUC: 0.9221 | Logloss: 0.2319 | Acc@0.5: 0.9070 | best_iter: 106
[Fold 4] AUC: 0.9157 | Logloss: 0.1932 | Acc@0.5: 0.9234 | best_iter: 232
[Fold 5] AUC: 0.9438 | Logloss: 0.1632 | Acc@0.5: 0.9296 | best_iter: 419
[Fold 6] AUC: 0.9400 | Logloss: 0.2243 | Acc@0.5: 0.9058 | best_iter: 145
[Fold 7] AUC: 0.9378 | Logloss: 0.2353 | Acc@0.5: 0.8888 | best_iter: 131
[Fold 8] AUC: 0.9354 | Logloss: 0.3001 | Acc@0.5: 0.8956 | best_iter: 58


[I 2026-01-19 03:02:27,220] Trial 14 finished with value: 0.934142541998742 and parameters: {'n_estimators': 2952, 'learning_rate': 0.028605448296408355, 'max_depth': 7, 'min_child_weight': 7.331017791598899, 'subsample': 0.7237856101217464, 'colsample_bytree': 0.9048375868758152, 'gamma': 1.4334210686951052, 'reg_lambda': 0.12933037743908263, 'reg_alpha': 3.02894819543668e-06}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9188 | Logloss: 0.2356 | Acc@0.5: 0.9012 | best_iter: 104
Trial 14: Avg AUC=0.9341 | Avg Logloss=0.2199 | Avg Acc@0.5=0.9094
[Fold 0] AUC: 0.9453 | Logloss: 0.1419 | Acc@0.5: 0.9455 | best_iter: 316
[Fold 1] AUC: 0.9402 | Logloss: 0.1738 | Acc@0.5: 0.9285 | best_iter: 131
[Fold 2] AUC: 0.9363 | Logloss: 0.2224 | Acc@0.5: 0.9081 | best_iter: 54
[Fold 3] AUC: 0.9242 | Logloss: 0.2143 | Acc@0.5: 0.9166 | best_iter: 59
[Fold 4] AUC: 0.9263 | Logloss: 0.1503 | Acc@0.5: 0.9455 | best_iter: 295
[Fold 5] AUC: 0.9405 | Logloss: 0.1877 | Acc@0.5: 0.9126 | best_iter: 109
[Fold 6] AUC: 0.9416 | Logloss: 0.2013 | Acc@0.5: 0.9154 | best_iter: 97
[Fold 7] AUC: 0.9387 | Logloss: 0.2214 | Acc@0.5: 0.9052 | best_iter: 63
[Fold 8] AUC: 0.9384 | Logloss: 0.2637 | Acc@0.5: 0.9001 | best_iter: 32


[I 2026-01-19 03:02:31,037] Trial 15 finished with value: 0.9352226064407642 and parameters: {'n_estimators': 322, 'learning_rate': 0.06714473539454825, 'max_depth': 8, 'min_child_weight': 12.67804173174696, 'subsample': 0.7331765485200763, 'colsample_bytree': 0.8940732121482251, 'gamma': 2.959710227497413, 'reg_lambda': 1.4218310453134289, 'reg_alpha': 0.0035046776626541727}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9207 | Logloss: 0.1920 | Acc@0.5: 0.9115 | best_iter: 91
Trial 15: Avg AUC=0.9352 | Avg Logloss=0.1969 | Avg Acc@0.5=0.9189
[Fold 0] AUC: 0.9497 | Logloss: 0.1403 | Acc@0.5: 0.9444 | best_iter: 788
[Fold 1] AUC: 0.9467 | Logloss: 0.1709 | Acc@0.5: 0.9302 | best_iter: 434
[Fold 2] AUC: 0.9345 | Logloss: 0.6113 | Acc@0.5: 0.8826 | best_iter: 8
[Fold 3] AUC: 0.9266 | Logloss: 0.2041 | Acc@0.5: 0.9274 | best_iter: 207
[Fold 4] AUC: 0.9174 | Logloss: 0.1926 | Acc@0.5: 0.9251 | best_iter: 270
[Fold 5] AUC: 0.9366 | Logloss: 0.2514 | Acc@0.5: 0.9007 | best_iter: 139
[Fold 6] AUC: 0.9409 | Logloss: 0.1963 | Acc@0.5: 0.9234 | best_iter: 311
[Fold 7] AUC: 0.9400 | Logloss: 0.2092 | Acc@0.5: 0.9081 | best_iter: 263


[I 2026-01-19 03:02:38,870] Trial 16 finished with value: 0.9350795924021623 and parameters: {'n_estimators': 1962, 'learning_rate': 0.0161839799181405, 'max_depth': 8, 'min_child_weight': 6.043783748911778, 'subsample': 0.8132056250276885, 'colsample_bytree': 0.8964593417508803, 'gamma': 1.2186785097580235, 'reg_lambda': 3.0809314741554017, 'reg_alpha': 0.003224200060190604}. Best is trial 10 with value: 0.9366294281009996.


[Fold 8] AUC: 0.9373 | Logloss: 0.2146 | Acc@0.5: 0.9103 | best_iter: 212
[Fold 9] AUC: 0.9211 | Logloss: 0.5267 | Acc@0.5: 0.8876 | best_iter: 20
Trial 16: Avg AUC=0.9351 | Avg Logloss=0.2718 | Avg Acc@0.5=0.9140
[Fold 0] AUC: 0.9502 | Logloss: 0.1573 | Acc@0.5: 0.9263 | best_iter: 162
[Fold 1] AUC: 0.9415 | Logloss: 0.1587 | Acc@0.5: 0.9359 | best_iter: 162
[Fold 2] AUC: 0.9369 | Logloss: 0.2009 | Acc@0.5: 0.9155 | best_iter: 69
[Fold 3] AUC: 0.9243 | Logloss: 0.1840 | Acc@0.5: 0.9308 | best_iter: 90
[Fold 4] AUC: 0.9237 | Logloss: 0.1664 | Acc@0.5: 0.9342 | best_iter: 135
[Fold 5] AUC: 0.9390 | Logloss: 0.2880 | Acc@0.5: 0.8995 | best_iter: 29
[Fold 6] AUC: 0.9405 | Logloss: 0.1901 | Acc@0.5: 0.9262 | best_iter: 115
[Fold 7] AUC: 0.9352 | Logloss: 0.2059 | Acc@0.5: 0.9092 | best_iter: 77
[Fold 8] AUC: 0.9317 | Logloss: 0.1997 | Acc@0.5: 0.9132 | best_iter: 91


[I 2026-01-19 03:02:43,065] Trial 17 finished with value: 0.9344906894949997 and parameters: {'n_estimators': 1694, 'learning_rate': 0.05132403153751253, 'max_depth': 9, 'min_child_weight': 11.7422878102704, 'subsample': 0.6858580468714496, 'colsample_bytree': 0.9972116788724801, 'gamma': 2.758436000857831, 'reg_lambda': 0.23124059933426286, 'reg_alpha': 3.039720460187768e-05}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9219 | Logloss: 0.1699 | Acc@0.5: 0.9262 | best_iter: 139
Trial 17: Avg AUC=0.9345 | Avg Logloss=0.1921 | Avg Acc@0.5=0.9217
[Fold 0] AUC: 0.9394 | Logloss: 0.2498 | Acc@0.5: 0.8843 | best_iter: 45
[Fold 1] AUC: 0.9441 | Logloss: 0.1675 | Acc@0.5: 0.9319 | best_iter: 166
[Fold 2] AUC: 0.9303 | Logloss: 0.2296 | Acc@0.5: 0.9030 | best_iter: 68
[Fold 3] AUC: 0.9219 | Logloss: 0.2484 | Acc@0.5: 0.8883 | best_iter: 43
[Fold 4] AUC: 0.9160 | Logloss: 0.2189 | Acc@0.5: 0.9109 | best_iter: 67
[Fold 5] AUC: 0.9420 | Logloss: 0.1856 | Acc@0.5: 0.9183 | best_iter: 132
[Fold 6] AUC: 0.9359 | Logloss: 0.2404 | Acc@0.5: 0.8939 | best_iter: 61
[Fold 7] AUC: 0.9331 | Logloss: 0.2352 | Acc@0.5: 0.8927 | best_iter: 67
[Fold 8] AUC: 0.9316 | Logloss: 0.2671 | Acc@0.5: 0.8882 | best_iter: 39


[I 2026-01-19 03:02:45,496] Trial 18 finished with value: 0.931397596050793 and parameters: {'n_estimators': 1106, 'learning_rate': 0.08976435765872764, 'max_depth': 6, 'min_child_weight': 5.814452865402799, 'subsample': 0.7752892097439209, 'colsample_bytree': 0.9353966462634985, 'gamma': 1.8085447631703297, 'reg_lambda': 0.16802253139463175, 'reg_alpha': 0.0003660237948995472}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9196 | Logloss: 0.1939 | Acc@0.5: 0.9154 | best_iter: 115
Trial 18: Avg AUC=0.9314 | Avg Logloss=0.2236 | Avg Acc@0.5=0.9027
[Fold 0] AUC: 0.9530 | Logloss: 0.1321 | Acc@0.5: 0.9467 | best_iter: 100
[Fold 1] AUC: 0.9426 | Logloss: 0.1433 | Acc@0.5: 0.9444 | best_iter: 85
[Fold 2] AUC: 0.9346 | Logloss: 0.1549 | Acc@0.5: 0.9325 | best_iter: 72
[Fold 3] AUC: 0.9243 | Logloss: 0.2093 | Acc@0.5: 0.9217 | best_iter: 20
[Fold 4] AUC: 0.9186 | Logloss: 0.1477 | Acc@0.5: 0.9518 | best_iter: 140
[Fold 5] AUC: 0.9387 | Logloss: 0.1465 | Acc@0.5: 0.9404 | best_iter: 101
[Fold 6] AUC: 0.9393 | Logloss: 0.1699 | Acc@0.5: 0.9330 | best_iter: 59
[Fold 7] AUC: 0.9362 | Logloss: 0.1967 | Acc@0.5: 0.9200 | best_iter: 38
[Fold 8] AUC: 0.9297 | Logloss: 0.2103 | Acc@0.5: 0.9058 | best_iter: 27


[I 2026-01-19 03:02:48,889] Trial 19 finished with value: 0.9338267246488302 and parameters: {'n_estimators': 762, 'learning_rate': 0.17852422458593126, 'max_depth': 9, 'min_child_weight': 13.308373242791912, 'subsample': 0.8315002433944294, 'colsample_bytree': 0.8584015616521465, 'gamma': 0.12218165996531316, 'reg_lambda': 3.30995288308445, 'reg_alpha': 8.325187703539956e-06}. Best is trial 10 with value: 0.9366294281009996.


[Fold 9] AUC: 0.9213 | Logloss: 0.2076 | Acc@0.5: 0.9103 | best_iter: 20
Trial 19: Avg AUC=0.9338 | Avg Logloss=0.1718 | Avg Acc@0.5=0.9307
Best params: {'n_estimators': 1162, 'learning_rate': 0.023962556929236718, 'max_depth': 10, 'min_child_weight': 8.99775502964076, 'subsample': 0.8106626806922802, 'colsample_bytree': 0.9881283795532174, 'gamma': 1.847361653297833, 'reg_lambda': 0.9569699786903291, 'reg_alpha': 2.5490266596638967e-06}
Best value (AUC): 0.9366294281009996


In [7]:
best_params = study.best_params
print(best_params)

{'n_estimators': 1162, 'learning_rate': 0.023962556929236718, 'max_depth': 10, 'min_child_weight': 8.99775502964076, 'subsample': 0.8106626806922802, 'colsample_bytree': 0.9881283795532174, 'gamma': 1.847361653297833, 'reg_lambda': 0.9569699786903291, 'reg_alpha': 2.5490266596638967e-06}


In [8]:
import numpy as np
import pandas as pd
from pathlib import Path

from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score, log_loss, accuracy_score, confusion_matrix
import joblib

BASE = Path.cwd()
artifacts_dir = BASE / "artifacts"

best_models_dir = artifacts_dir / "xgb_best_models"
best_models_dir.mkdir(parents=True, exist_ok=True)

final_ckpt_dir = BASE / "checkpoints_xgb_best"
final_ckpt_dir.mkdir(parents=True, exist_ok=True)

print("Best hyperparameters from Optuna:", best_params)

final_fold_metrics = []

for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\n==================== Final XGBoost training for fold {fold_idx} ====================")

    X_train = X[tr_idx]
    y_train = np.asarray(y[tr_idx]).astype(int)

    X_val = X[val_idx]
    y_val = np.asarray(y[val_idx]).astype(int)

    # scale_pos_weight (train fold only)
    pos = y_train.sum()
    neg = y_train.size - pos
    scale_pos_weight = float(neg / (pos + 1e-12))

    model = XGBClassifier(
        objective="binary:logistic",
        eval_metric="auc",            # aligns with optimizing AUC
        early_stopping_rounds=50,
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
        **best_params,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )

    probs = model.predict_proba(X_val)[:, 1]
    preds = (probs >= 0.5).astype(int)

    auc = roc_auc_score(y_val, probs)
    ll  = log_loss(y_val, probs, labels=[0, 1])
    acc = accuracy_score(y_val, preds)

    cm = confusion_matrix(y_val, preds)
    tn, fp, fn, tp = cm.ravel()

    best_iter = getattr(model, "best_iteration", None)

    # Save model (per fold)
    model_path = best_models_dir / f"xgb_best_fold_{fold_idx}.joblib"
    joblib.dump(model, model_path)

    print(f"[Fold {fold_idx}] Saved model to: {model_path}")
    print(f"[Fold {fold_idx}] AUC: {auc:.4f} | Logloss: {ll:.4f} | Acc@0.5: {acc:.4f} | best_iter: {best_iter}")
    print(f"[Fold {fold_idx}] CM TN={tn} FP={fp} FN={fn} TP={tp}")

    final_fold_metrics.append({
        "Fold": fold_idx,
        "AUC": float(auc),
        "Logloss": float(ll),
        "Accuracy@0.5": float(acc),
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp),
        "Best_Iteration": best_iter,
        "Scale_Pos_Weight": scale_pos_weight,
        "Model_Path": str(model_path),
    })

metrics_df = pd.DataFrame(final_fold_metrics)
metrics_path = best_models_dir / "xgb_best_models_summary.csv"
metrics_df.to_csv(metrics_path, index=False)

print("\n✅ Saved summary of best XGBoost models across folds to:", metrics_path)
print(metrics_df)


Best hyperparameters from Optuna: {'n_estimators': 1162, 'learning_rate': 0.023962556929236718, 'max_depth': 10, 'min_child_weight': 8.99775502964076, 'subsample': 0.8106626806922802, 'colsample_bytree': 0.9881283795532174, 'gamma': 1.847361653297833, 'reg_lambda': 0.9569699786903291, 'reg_alpha': 2.5490266596638967e-06}

==================== Final XGBoost training for fold 0 ====================
[Fold 0] Saved model to: /Users/sdl5_mp/Documents/SDL5_MP/transfer_learning/artifacts/xgb_best_models/xgb_best_fold_0.joblib
[Fold 0] AUC: 0.9507 | Logloss: 0.1311 | Acc@0.5: 0.9484 | best_iter: 502
[Fold 0] CM TN=1620 FP=66 FN=25 TP=52

==================== Final XGBoost training for fold 1 ====================
[Fold 1] Saved model to: /Users/sdl5_mp/Documents/SDL5_MP/transfer_learning/artifacts/xgb_best_models/xgb_best_fold_1.joblib
[Fold 1] AUC: 0.9456 | Logloss: 0.1445 | Acc@0.5: 0.9433 | best_iter: 315
[Fold 1] CM TN=1617 FP=76 FN=24 TP=46

==================== Final XGBoost training for 

In [9]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix
import joblib

confusion_matrices = []

for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\n===== Confusion matrix for fold {fold_idx} =====")

    # Validation data
    X_val = X[val_idx]
    y_val = y[val_idx].astype(int)

    # Load best XGBoost model for this fold
    model_path = best_models_dir / f"xgb_best_fold_{fold_idx}.joblib"
    model = joblib.load(model_path)

    # Predict probabilities (class 1 = high MP)
    probs = model.predict_proba(X_val)[:, 1]
    preds = (probs >= 0.5).astype(int)

    # Confusion matrix
    cm = confusion_matrix(y_val, preds, labels=[0, 1])
    confusion_matrices.append(cm)

    print("Confusion matrix (rows=true, cols=pred):")
    print(cm)

    tn, fp, fn, tp = cm.ravel()
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")



===== Confusion matrix for fold 0 =====
Confusion matrix (rows=true, cols=pred):
[[1620   66]
 [  25   52]]
TN=1620, FP=66, FN=25, TP=52

===== Confusion matrix for fold 1 =====
Confusion matrix (rows=true, cols=pred):
[[1617   76]
 [  24   46]]
TN=1617, FP=76, FN=24, TP=46

===== Confusion matrix for fold 2 =====
Confusion matrix (rows=true, cols=pred):
[[1596   89]
 [  24   54]]
TN=1596, FP=89, FN=24, TP=54

===== Confusion matrix for fold 3 =====
Confusion matrix (rows=true, cols=pred):
[[1615   86]
 [  17   45]]
TN=1615, FP=86, FN=17, TP=45

===== Confusion matrix for fold 4 =====
Confusion matrix (rows=true, cols=pred):
[[1614   60]
 [  37   52]]
TN=1614, FP=60, FN=37, TP=52

===== Confusion matrix for fold 5 =====
Confusion matrix (rows=true, cols=pred):
[[1612   75]
 [  27   48]]
TN=1612, FP=75, FN=27, TP=48

===== Confusion matrix for fold 6 =====
Confusion matrix (rows=true, cols=pred):
[[1573   88]
 [  26   75]]
TN=1573, FP=88, FN=26, TP=75

===== Confusion matrix for fold 7

In [10]:
import numpy as np
import pandas as pd

mean_cm = np.mean(confusion_matrices, axis=0)

mean_cm_df = pd.DataFrame(
    mean_cm,
    index=["True Low&Int", "True High"],
    columns=["Pred Low&Int", "Pred High"],
)

print("\n===== Mean confusion matrix across folds (XGBoost) =====")
print(mean_cm_df)

# Save to CSV (use an XGB-specific name)
mean_cm_path = best_models_dir / "xgb_mean_confusion_matrix.csv"
mean_cm_df.to_csv(mean_cm_path, index=True)
print(f"\n✅ Saved mean confusion matrix to: {mean_cm_path}")



===== Mean confusion matrix across folds (XGBoost) =====
              Pred Low&Int  Pred High
True Low&Int        1600.4       84.9
True High             24.8       52.4

✅ Saved mean confusion matrix to: /Users/sdl5_mp/Documents/SDL5_MP/transfer_learning/artifacts/xgb_best_models/xgb_mean_confusion_matrix.csv


In [11]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import joblib

def metrics_from_confusion(cm):
    """
    cm = [[TN, FP],
          [FN, TP]]
    """
    TN, FP, FN, TP = cm.ravel()

    accuracy  = (TP + TN) / (TP + TN + FP + FN)
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1        = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    specificity = TN / (TN + FP) if (TN + FP) > 0 else 0.0

    return {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Specificity": specificity,
    }

all_fold_metrics = []
all_conf_matrices = []

for fold_idx, (tr_idx, val_idx) in enumerate(folds):
    print(f"\nEvaluating fold {fold_idx}")

    # Load best XGBoost model for this fold
    model_path = best_models_dir / f"xgb_best_fold_{fold_idx}.joblib"
    model = joblib.load(model_path)

    # Validation data
    X_val = X[val_idx]
    y_val = y[val_idx].astype(int)

    # Predict probabilities + labels
    probs = model.predict_proba(X_val)[:, 1]
    preds = (probs >= 0.5).astype(int)

    # Confusion matrix: [[TN, FP], [FN, TP]]
    cm = confusion_matrix(y_val, preds, labels=[0, 1])
    all_conf_matrices.append(cm)

    # Metrics
    metrics = metrics_from_confusion(cm)
    metrics["Fold"] = fold_idx
    all_fold_metrics.append(metrics)

    print("Confusion matrix:\n", cm)
    print(metrics)

# Optional: turn metrics into a DataFrame
df_metrics = pd.DataFrame(all_fold_metrics)
print("\nPer-fold metrics:")
print(df_metrics)

# Optional: mean confusion matrix across folds
mean_cm = np.mean(all_conf_matrices, axis=0)
mean_cm_df = pd.DataFrame(mean_cm, index=["True 0", "True 1"], columns=["Pred 0", "Pred 1"])
print("\nMean confusion matrix across folds:")
print(mean_cm_df)



Evaluating fold 0
Confusion matrix:
 [[1620   66]
 [  25   52]]
{'Accuracy': np.float64(0.9483834373227453), 'Precision': np.float64(0.4406779661016949), 'Recall': np.float64(0.6753246753246753), 'F1': np.float64(0.5333333333333333), 'Specificity': np.float64(0.9608540925266904), 'Fold': 0}

Evaluating fold 1
Confusion matrix:
 [[1617   76]
 [  24   46]]
{'Accuracy': np.float64(0.9432785025524674), 'Precision': np.float64(0.3770491803278688), 'Recall': np.float64(0.6571428571428571), 'F1': np.float64(0.47916666666666663), 'Specificity': np.float64(0.9551092734790313), 'Fold': 1}

Evaluating fold 2
Confusion matrix:
 [[1596   89]
 [  24   54]]
{'Accuracy': np.float64(0.9359047078842881), 'Precision': np.float64(0.3776223776223776), 'Recall': np.float64(0.6923076923076923), 'F1': np.float64(0.48868778280542974), 'Specificity': np.float64(0.9471810089020771), 'Fold': 2}

Evaluating fold 3
Confusion matrix:
 [[1615   86]
 [  17   45]]
{'Accuracy': np.float64(0.9415768576290414), 'Precisio

In [12]:
metrics_df = pd.DataFrame(all_fold_metrics)

mean_metrics = metrics_df.mean(numeric_only=True)
std_metrics  = metrics_df.std(numeric_only=True)

summary_df = pd.DataFrame({
    "Mean": mean_metrics,
    "Std": std_metrics
})

print("\n=== Cross-validated performance ===")
print(summary_df)



=== Cross-validated performance ===
                 Mean       Std
Accuracy     0.937757  0.010041
Precision    0.385367  0.054430
Recall       0.679058  0.045356
F1           0.488550  0.041949
Specificity  0.949620  0.011303
Fold         4.500000  3.027650
